In [3]:
import argparse
import pyprind

import numpy as np
import pandas as pd

from scipy.spatial.distance import cdist
from scipy.interpolate import interp1d
from scipy import stats

from fancyimpute import KNN

In [4]:
print('Loading processed files created from database using "preprocess.py"')
abx           = pd.read_csv('processed_files/abx.csv',           sep = '|')
culture       = pd.read_csv('processed_files/culture.csv',       sep = '|')
microbio      = pd.read_csv('processed_files/microbio.csv',      sep = '|')
demog         = pd.read_csv('processed_files/demog.csv',         sep = '|')
ce010         = pd.read_csv('processed_files/ce010000.csv',      sep = '|')
ce1020        = pd.read_csv('processed_files/ce1000020000.csv',  sep = '|')
ce2030        = pd.read_csv('processed_files/ce2000030000.csv',  sep = '|')
ce3040        = pd.read_csv('processed_files/ce3000040000.csv',  sep = '|')
ce4050        = pd.read_csv('processed_files/ce4000050000.csv',  sep = '|')
ce5060        = pd.read_csv('processed_files/ce5000060000.csv',  sep = '|')
ce6070        = pd.read_csv('processed_files/ce6000070000.csv',  sep = '|')
ce7080        = pd.read_csv('processed_files/ce7000080000.csv',  sep = '|')
ce8090        = pd.read_csv('processed_files/ce8000090000.csv',  sep = '|')
ce90100       = pd.read_csv('processed_files/ce90000100000.csv', sep = '|')
MV            = pd.read_csv('processed_files/mechvent.csv',      sep = '|')
inputpreadm   = pd.read_csv('processed_files/preadm_fluid.csv',  sep = '|')
inputMV       = pd.read_csv('processed_files/fluid_mv.csv',      sep = '|')
inputCV       = pd.read_csv('processed_files/fluid_cv.csv',      sep = '|')
vasoMV        = pd.read_csv('processed_files/vaso_mv.csv',       sep = '|')
vasoCV        = pd.read_csv('processed_files/vaso_cv.csv',       sep = '|')
UOpreadm      = pd.read_csv('processed_files/preadm_uo.csv',     sep = '|')
UO            = pd.read_csv('processed_files/uo.csv',            sep = '|')
labU          = [pd.read_csv('processed_files/labs_ce.csv', sep = '|') , pd.read_csv('processed_files/labs_le.csv', sep = '|')]

labU[1].rename(columns = {'timestp': 'charttime'}, inplace=True) 
labU = pd.concat(labU, sort=False, ignore_index=True)

Loading processed files created from database using "preprocess.py"

In [5]:
# Initial data manipulations
microbio['charttime'] = microbio['charttime'].fillna(microbio['chartdate'])
del microbio['chartdate']
bacterio = pd.concat([microbio, culture], sort=False, ignore_index=True)

demog['morta_90'].fillna(0, inplace=True)
demog['morta_hosp'].fillna(0, inplace=True)
demog['elixhauser'].fillna(0, inplace=True)

In [6]:
# Keep only the first icustay of an admission (CRITICAL FIX FROM MATLAB CODE)
demog = demog.drop_duplicates(subset=['admittime','dischtime'],keep='first')

In [7]:
# Get list of all icustayids since that's what we iterate over through the rest of this script
# The old code had a continuous range of icustayids so it was easy to loop through them with a range(numIDS),
# Since we're only keeping the first icustay of a patient's admission, this is now different...
icustayidlist = list(demog.icustay_id.values)

In [8]:
print(len(icustayidlist))

57786

In [9]:
# Calculate the accurate readmission using the demographics data 
# (the SQL code from Komorowski, et al incorrectly cumulatively counts how many icu stays each patient has (preprocess.py:line 414) 
# and does a coarse boolean check if this number is >1). A readmission is now correctly defined by 
# whether the patient has returned to the ICU within 30 days of being previously discharged.

# This is done by grouping all the discharge times for each patient and using them in a comparison 
# with the current row's admission time to see if it's within the 30 day cutoff
subj_dischtime_list = demog.sort_values(by='admittime').groupby('subject_id').apply(lambda df: np.unique(df.dischtime.values)) # Create list of discharge times for each patient (output is a dict keyed by 'subject_id')

In [10]:
print(len(subj_dischtime_list))

46476

In [11]:
def determine_readmission(s, dischtimes=subj_dischtime_list,cutoff=3600*24*30):
    '''
    determine_readmisson evaluates each row of the provided dataframe (designed to operate on the demographics table)
    and chooses whether the current admission occurs within the cutoff of the previous discharge 
    (here, cutoff=30 days is the default)
    '''
    subject, admission, discharge = s[['subject_id','admittime','dischtime']]
    
    # Check for readmission
    subj_stay_idx = np.where(dischtimes[subject]==discharge)[0][0]
    s['re_admission'] = 0
    if subj_stay_idx > 0:
        if (admission - dischtimes[subject][subj_stay_idx-1]) <= cutoff:
            s['re_admission'] = 1
            
    return s

In [12]:
demog = demog.apply(determine_readmission,axis=1)

In [13]:
demog

,subject_id,hadm_id,icustay_id,admittime,dischtime,adm_order,unit,intime,outtime,los,age,dob,dod,expire_flag,gender,morta_hosp,morta_90,elixhauser,re_admission
0,2.0,163353.0,243653.0,5.318680e+09,5.319014e+09,1.0,5.0,5.318688e+09,5.318696e+09,0.0918,0.888970,5.318611e+09,NaN,0.0,1.0,0.0,0.0,0.0,0.0
1,3.0,145834.0,211552.0,4.159278e+09,4.160210e+09,1.0,1.0,4.159279e+09,4.159803e+09,6.0646,27950.798738,1.744330e+09,4.179686e+09,1.0,1.0,0.0,0.0,2.0,0.0
2,4.0,185777.0,294638.0,6.980517e+09,6.981187e+09,1.0,1.0,6.980517e+09,6.980662e+09,1.6785,17475.020498,5.470675e+09,NaN,0.0,2.0,0.0,0.0,3.0,0.0
3,5.0,178980.0,214757.0,4.199834e+09,4.200034e+09,1.0,5.0,4.199839e+09,4.199847e+09,0.0844,0.253056,4.199818e+09,NaN,0.0,1.0,0.0,0.0,0.0,0.0
4,6.0,107064.0,228232.0,6.482100e+09,6.483514e+09,1.0,2.0,6.482151e+09,6.482468e+09,3.6729,24084.896458,4.401216e+09,NaN,0.0,2.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61527,99985.0,176670.0,279638.0,6.660845e+09,6.662279e+09,1.0,1.0,6.661028e+09,6.662004e+09,11.2998,19655.231644,4.962816e+09,NaN,0.0,1.0,0.0,0.0,1.0,0.0
61528,99991.0,151118.0,226241.0,6.784159e+09,6.785209e+09,1.0,3.0,6.784537e+09,6.784808e+09,3.1426,17432.729838,5.278349e+09,NaN,0.0,1.0,0.0,0.0,4.0,0.0
61529,99992.0,197084.0,242052.0,5.508756e+09,5.509015e+09,1.0,1.0,5.508756e+09,5.508927e+09,1.9745,24022.753264,3.433190e+09,NaN,0.0,2.0,0.0,0.0,2.0,0.0
61530,99995.0,137810.0,229633.0,5.588899e+09,5.589177e+09,1.0,4.0,5.588920e+09,5.589107e+09,2.1615,32396.579144,2.789856e+09,5.609002e+09,1.0,2.0,0.0,0.0,4.0,0.0
61531,99999.0,113369.0,246512.0,4.670292e+09,4.670757e+09,1.0,2.0,4.670395e+09,4.670492e+09,1.1242,23369.494861,2.651270e+09,NaN,0.0,2.0,0.0,0.0,2.0,0.0

## **Help Function**

In [16]:
def SAH(input, vitalslab_hold, adjust=0):
    '''Matthieu Komorowski - Imperial College London 2017 
    will copy a value in the rows below if the missing values are within the
    hold period for this variable (e.g. 48h for weight, 2h for HR...)
    vitalslab_hold = 2x55 cell (with row1 = strings of names ; row 2 = hold time)'''
    temp = np.copy(input)
    hold = vitalslab_hold.values[0, :]
    nrow, ncol = temp.shape

    lastcharttime = np.zeros(ncol)
    lastvalue = np.zeros(ncol)
    oldstayid = temp[0, 1]

    bar_SAH = pyprind.ProgBar(ncol-(3+adjust))
    for i in range(3+adjust,ncol):
        bar_SAH.update()
        for j in range(nrow):
            if oldstayid != temp[j, 1]:
                lastcharttime = np.zeros(ncol)
                lastvalue = np.zeros(ncol)
                oldstayid = temp[j, 1]
            if not np.isnan(temp[j, i]):
                lastcharttime[i] = temp[j, 2]
                lastvalue[i] = temp[j, i]
            if j > 0:
                if (np.isnan(temp[j, i])) and (temp[j, 1] == oldstayid) and ((temp[j, 2] - lastcharttime[i]) <= hold[i-(3+adjust)]*3600):
                    temp[j,i] = lastvalue[i]
    return temp

In [17]:
def fixgaps(x):
    '''FIXGAPS Linearly interpolates gaps in a time series
    YOUT=FIXGAPS(YIN) linearly interpolates over NaN
    in the input time series (may be complex), but ignores
    trailing and leading NaN.
    R. Pawlowicz 6/Nov/99'''
    y = np.copy(x)
    bd = np.isnan(x)
    gd = np.arange(len(x))[~bd]
    bd[:min(gd)] = False
    bd[max(gd)+1:] = False
    y[bd] = interp1d(gd,x[gd])(np.arange(len(x))[bd])
    return y

In [18]:
def deloutabove(a, col_no, a_max):
    a[a[:,col_no] > a_max, col_no] = np.nan 
    return a

def deloutbelow(a, col_no, a_min):
    a[a[:,col_no] < a_min, col_no] = np.nan 
    return a

## Filling missing icuid

In [19]:
# Compute normalized rate of infusion
# if 100 ml of hypertonic fluid (600 mosm/l) is given at 100 ml/h (given in 1h) it is 200 ml of NS equivalent
# so the normalized rate of infusion is 200 ml/h (different volume in same duration)
inputMV['norm_rate_of_infusion'] = inputMV['tev']*inputMV['rate']/inputMV['amount']

In [20]:
# Fill-in missing ICUSTAY IDs in bacterio
print('Filling-in missing ICUSTAY IDs in bacterio')
bar = pyprind.ProgBar(len(bacterio.index.tolist()))
# Raw Translation
for i in bacterio.index.tolist():
    bar.update()
    if np.isnan(bacterio.loc[i, 'icustay_id']):
        o         = bacterio.loc[i, 'charttime'] 
        subjectid = bacterio.loc[i, 'subject_id']
        hadmid    = bacterio.loc[i, 'hadm_id']
        ii        = demog.index[demog['subject_id'] == subjectid].tolist()
        jj        = demog.index[(demog['subject_id'] == subjectid) & (demog['hadm_id'] == hadmid)].tolist()
        for j in range(len(ii)):
            if (o >= demog.loc[ii[j], 'intime'] - 48*3600) and (o <= demog.loc[ii[j], 'outtime'] + 48*3600):
                bacterio.loc[i,'icustay_id'] = demog.loc[ii[j], 'icustay_id']
            elif len(ii)==1:   # If we cant confirm from admission and discharge time but there is only 1 admission: it's the one!!
                bacterio.loc[i,'icustay_id'] = demog.loc[ii[j], 'icustay_id']

Filling-in missing ICUSTAY IDs in bacterio
Warning: No valid output stream.

In [21]:
print('Filling-in missing ICUSTAY IDs in bacterio - 2')                
bar = pyprind.ProgBar(len(bacterio.index.tolist()))
for i in bacterio.index.tolist():
    bar.update()
    if np.isnan(bacterio.loc[i, 'icustay_id']):
        subjectid = bacterio.loc[i, 'subject_id']
        hadmid    = bacterio.loc[i, 'hadm_id']
        jj        = demog.index[(demog['subject_id'] == subjectid) & (demog['hadm_id'] == hadmid)].tolist()
        if len(jj) == 1:
            bacterio.loc[i,'icustay_id'] = demog.loc[jj[0], 'icustay_id']

Filling-in missing ICUSTAY IDs in bacterio - 2
Warning: No valid output stream.

In [22]:
# Fill-in missing ICUSTAY IDs in Antibiotics administration
print('Filling-in missing ICUSTAY IDs in ABx')
bar = pyprind.ProgBar(len(abx.index.tolist()))
for i in abx.index.tolist():
    bar.update()
    if np.isnan(abx.loc[i,'icustay_id']):
        o      = abx.loc[i,'startdate']  #time of event
        hadmid = abx.loc[i,'hadm_id']
        ii     = demog.index[demog['hadm_id'] == hadmid].tolist()
        for j in range(len(ii)):
            if o >= demog.loc[ii[j],'intime'] - 48*3600 and o <= demog.loc[ii[j], 'outtime'] + 48*3600:
                abx.loc[i, 'icustay_id'] = demog.loc[ii[j], 'icustay_id']
            elif len(ii) == 1:   #if we cant confirm from admission and discharge time but there is only 1 admission: it's the one!!
                abx.loc[i, 'icustay_id'] = demog.loc[ii[j], 'icustay_id']

Filling-in missing ICUSTAY IDs in ABx
Warning: No valid output stream.

In [23]:
print('Full ICU -- Finding presumed onset of infection according to sepsis3 guidelines')
# 根据Sepsis-3指南确定每个ICU病人的感染发病时间

onset = dict()
num_onset = 0
bar = pyprind.ProgBar(len(icustayidlist))
for icustayid in icustayidlist:
    bar.update()
    onset[icustayid] = np.zeros(3)
    ab = abx.loc[abx['icustay_id'] == icustayid, 'startdate']   # Start time of abx for this icustayid
    bact = bacterio.loc[bacterio['icustay_id'] == icustayid, 'charttime']   # Time of sample
    subj_bact = bacterio.loc[bacterio['icustay_id'] == icustayid,'subject_id'] 
    
    if len(ab) > 0 and len(bact) > 0:   # If we have data for both: proceed
        # Pairwise distances between antibiotic adminstration and requested cultures, in hours
        D = cdist(ab.values.reshape(ab.values.shape[0],1),bact.values.reshape(bact.values.shape[0],1))/3600  
        for i in range(D.shape[0]):  #looping through all rows of adminsitered antibiotics, from early to late
            M, I = np.min(D[i,:]), np.argmin(D[i,:])        # minimum distance in this row
            ab1 = ab.iloc[i]       # timestamp of this value in list of antibiotics
            bact1 = bact.iloc[I]   # timestamp in list of cultures
            if M <= 24 and ab1 <= bact1:      # if ab was first and delay < 24h
                onset[icustayid][0] = subj_bact.iloc[0]
                onset[icustayid][1] = icustayid  
                onset[icustayid][2] = ab1     # Onset of infection = abx time
                num_onset += 1
                break
            elif M <= 72 and ab1 >= bact1:    # elseif sample was first and delay < 72h
                onset[icustayid][0] = subj_bact.iloc[0]   
                onset[icustayid][1] = icustayid
                onset[icustayid][2] = bact1       # Onset of infection = sample time
                num_onset += 1
                break

Full ICU -- Finding presumed onset of infection according to sepsis3 guidelines
Warning: No valid output stream.

In [24]:
# Sum of records found
# 败血症的病历数量
print('Full ICU -- Number of preliminary, presumed septic trajectories: ', num_onset)

Full ICU -- Number of preliminary, presumed septic trajectories:  25367

In [27]:
# Replacing item_ids with column numbers from reference tables
print('Full ICU -- Replacing item_ids with column numbers from reference tables')

# Replace itemid in labs with column number
# This will accelerate process later
Reflabs = pd.read_csv("ReferenceFiles/Reflabs.tsv", sep = '\t', header=None)
Reflabs_values = np.unique(Reflabs.fillna(-10000))[1:]
Reflabs_id_dict = {}
for r in Reflabs_values:
    try:
        Reflabs_id_dict[r] = np.max(np.where(Reflabs.values == r)[0]) + 1 # for row: +1 due to Index correction python        
    except:
        print(r)
        break
itemid_col = labU.columns.tolist().index('itemid')
labU_temp = labU.values
for c in range(labU_temp.shape[0]):
    labU_temp[c,itemid_col] = Reflabs_id_dict[labU_temp[c,itemid_col]]
for i, c in enumerate(labU.columns.tolist()):
    labU.loc[:,c] = labU_temp[:,i]


# Replace itemid in vitals with col number
Refvitals = pd.read_csv("ReferenceFiles/Refvitals.tsv", sep = '\t', header=None)
Refvitals_values = np.unique(Refvitals.fillna(-10000))[1:]
Refvitals_id_dict = {}
for r in Refvitals_values:
    Refvitals_id_dict[r] = np.max(np.where(Refvitals.values == r)[0]) + 1 # +1 due to index correction for Python from MATLAB
ce_dfs = [ce010, ce1020, ce2030, ce3040, ce4050, ce5060, ce6070, ce7080, ce8090, ce90100]
for ce_df in ce_dfs:
    itemid_col = ce_df.columns.tolist().index('itemid')
    ce_df_temp = ce_df.values
    for c in range(ce_df_temp.shape[0]):
        ce_df_temp[c,itemid_col] = Refvitals_id_dict[ce_df_temp[c,itemid_col]]
    for i, c in enumerate(ce_df.columns.tolist()):
        ce_df.loc[:,c] = ce_df_temp[:,i]

Full ICU -- Replacing item_ids with column numbers from reference tables

In [35]:
# 确定感染的推定发病时间，并在特定时间窗口内收集病人的数据。
print(' Full ICU --  Making an array with all unique charttime (1 per row) and all items in columns.')
reformat = np.nan*np.ones((2000000,68))  # Final table 
qstime = dict()
winb4 = 25   # Lower limit for inclusion of data (24h before time flag)
winaft = 49  # Upper limit (48h after)
irow = 0  # Recording row for summary table
bar = pyprind.ProgBar(len(icustayidlist))
for icustayid in icustayidlist:
    qstime[icustayid] = np.zeros(4)
    bar.update()
    qst = onset[icustayid][2] #flag for presumed infection
    if qst > 0:  # if we have a flag
        d1 = demog.loc[demog['icustay_id'] == icustayid, ['age', 'dischtime']].values[0] # Age of patient + discharge time
        if d1[0] > 6574:  # If older than 18 years old
            # CHARTEVENTS
            if (icustayid-200000) < 10000:
                temp=ce010
            elif (icustayid-200000) < 20000:
                temp=ce1020
            elif (icustayid-200000) < 30000:
                temp=ce2030
            elif (icustayid-200000) < 40000:
                temp=ce3040
            elif (icustayid-200000) < 50000:
                temp=ce4050
            elif (icustayid-200000) < 60000:
                temp=ce5060
            elif (icustayid-200000) < 70000:
                temp=ce6070
            elif (icustayid-200000) < 80000:
                temp=ce7080
            elif (icustayid-200000) < 90000:
                temp=ce8090
            else:
                temp=ce90100
            temp = temp[temp['icustay_id'] == icustayid]

            ii = (temp['charttime'] >= qst - (winb4+4)*3600) & (temp['charttime'] <= qst + (winaft+4)*3600) # Time period of interest -4h and +4h
            temp = temp.loc[ii]   # Only time period of interest

            # LABEVENTS
            ii = labU['icustay_id'] == icustayid
            temp2 = labU.loc[ii]
            ii = (temp2['charttime'] >= qst - (winb4+4)*3600) & (temp2['charttime'] <= qst + (winaft+4)*3600) # Time period of interest -4h and +4h
            temp2 = temp2.loc[ii]   # Only time period of interest

            # Mech Vent + ?extubated
            ii = MV['icustay_id'] == icustayid
            temp3 = MV.loc[ii]
            ii = (temp3['charttime'] >= qst - (winb4+4)*3600) & (temp3['charttime'] <= qst + (winaft+4)*3600) # Time period of interest -4h and +4h
            temp3 = temp3.loc[ii]   #only time period of interest
            t = np.unique(pd.concat([temp['charttime'], temp2['charttime'], temp3['charttime']], ignore_index=True).values) # List of unique timestamps from all 3 sources / sorted in ascending order
 
            if len(t) > 0:
                for i in range(len(t)):
                    #CHARTEVENTS
                    ii = temp['charttime'] == t[i]
                    col = temp.loc[ii,'itemid']
                    value = temp.loc[ii,'valuenum']
                    reformat[irow, 0] = i+1 #timestep  
                    reformat[irow, 1] = icustayid
                    reformat[irow, 2] = t[i] #charttime
                    reformat[irow, 2+col.astype(int).values] = value.values # Store available values

                    # LAB VALUES
                    ii = temp2['charttime'] == t[i]
                    col = temp2.loc[ii, 'itemid']
                    value = temp2.loc[ii, 'valuenum']
                    reformat[irow, 30+col.astype(int).values] = value.values  # Store available values
                
                    # Mechanical Ventilation  
                    ii = temp3['charttime'] == t[i]
                    if np.nansum(ii) > 0:
                        col = temp3.loc[ii, 'mechvent']
                        value = temp3.loc[ii, 'extubated']
                        reformat[irow, 66] = col.values[0] # Store available values
                        reformat[irow, 67] = value.values[0] # Store available values
                    else:
                        reformat[irow, 66]= np.nan
                        reformat[irow, 67]= np.nan
                    irow += 1

                qstime[icustayid][0] = qst # Flag for presumed infection / this is time of sepsis if SOFA >=2 for this patient
                # SAVE FIRST and LAST TIMESTAMPS, in QSTIME, for each ICUSTAYID
                qstime[icustayid][1] = t[0]   # First timestamp
                qstime[icustayid][2] = t[-1]  # Last timestamp
                qstime[icustayid][3] = d1[1]  # Discharge time

reformat = np.delete(reformat, range(irow, len(reformat)) ,axis=0)  # Delete unused rows

 Full ICU --  Making an array with all unique charttime (1 per row) and all items in columns.
Warning: No valid output stream.

In [36]:
print('Full ICU -- Handling outliers')

# Weight
reformat = deloutabove(reformat, 4, 300) 

# Heart Rate
reformat = deloutabove(reformat, 7, 250)

# Blood Pressure
reformat = deloutabove(reformat, 8, 300)
reformat = deloutbelow(reformat, 9, 0) 
reformat = deloutabove(reformat, 9, 200)
reformat = deloutbelow(reformat, 10, 0) 
reformat = deloutabove(reformat, 10, 200) 

# Respiratory Rate
reformat = deloutabove(reformat, 11, 80) 

# SpO2
reformat = deloutabove(reformat, 12, 150) 
reformat[reformat[:, 12]>100, 12] = 100

# Temperature
reformat[(reformat[:, 13] > 90) & (np.isnan(reformat[:, 14])), 14] = reformat[(reformat[:, 13] > 90) & (np.isnan(reformat[:, 14])), 13]
reformat = deloutabove(reformat, 13, 90) 

# Interface / is in col 22
# FiO2
reformat = deloutabove(reformat, 22, 100) 
reformat[reformat[:, 22] < 1 , 22] = reformat[reformat[:,22] < 1 , 22]*100

reformat = deloutbelow(reformat, 22, 20) 
reformat = deloutabove(reformat, 23, 1.5)

# O2 FLOW
reformat = deloutabove(reformat, 24, 70)

#PEEP
reformat=deloutbelow(reformat, 25, 0) 
reformat=deloutabove(reformat, 25, 40) 

# Total Volume
reformat=deloutabove(reformat, 26, 1800)

# Mean Volume
reformat=deloutabove(reformat, 27, 50)

# Potassium
reformat=deloutbelow(reformat, 31, 1) 
reformat=deloutabove(reformat, 31, 15) 

# Sodium
reformat=deloutbelow(reformat, 32, 95) 
reformat=deloutabove(reformat, 32, 178)

# Chloride
reformat=deloutbelow(reformat, 33, 70) 
reformat=deloutabove(reformat, 33, 150)

# Glucose
reformat=deloutbelow(reformat, 34, 1) 
reformat=deloutabove(reformat, 34, 1000)

# Creatinine
reformat=deloutabove(reformat, 36, 150)

# Magnesium
reformat=deloutabove(reformat, 37, 10)

# Calcium
reformat=deloutabove(reformat, 38, 20)

# Ionized Calcium
reformat=deloutabove(reformat, 39, 5) 

# CO2
reformat=deloutabove(reformat, 40, 120) 

# SGPT/SGOT
reformat=deloutabove(reformat, 41, 10000) 
reformat=deloutabove(reformat, 42, 10000) 

# Hb/Ht
reformat=deloutabove(reformat, 49, 20) 
reformat=deloutabove(reformat, 50, 65) 

# White Blood Cells
reformat=deloutabove(reformat, 52, 500) 

# Platelets
reformat=deloutabove(reformat, 53, 2000)

# INR
reformat=deloutabove(reformat, 57, 20) 

# pH
reformat=deloutbelow(reformat, 58, 6.7) 
reformat=deloutabove(reformat, 58, 8) 

# pO2
reformat=deloutabove(reformat, 59, 700)

# pCO2
reformat=deloutabove(reformat, 60, 200)

# Base Excess
reformat=deloutbelow(reformat, 61, -50)

# Lactate
reformat=deloutabove(reformat, 62, 30)

Full ICU -- Handling outliers

In [37]:
# Estimate GCS from RASS - data from Wesley JAMA 2003
reformat[(np.isnan(reformat[:, 5])) & (reformat[:, 6] >= 0), 5] = 15
reformat[(np.isnan(reformat[:, 5])) & (reformat[:, 6] == -1), 5] = 14
reformat[(np.isnan(reformat[:, 5])) & (reformat[:, 6] == -2), 5] = 12
reformat[(np.isnan(reformat[:, 5])) & (reformat[:, 6] == -3), 5] = 11
reformat[(np.isnan(reformat[:, 5])) & (reformat[:, 6] == -4), 5] = 6
reformat[(np.isnan(reformat[:, 5])) & (reformat[:, 6] == -5), 5] = 3

# FiO2
reformat[(~np.isnan(reformat[:, 22])) & (np.isnan(reformat[:, 23])), 23] = reformat[(~np.isnan(reformat[:, 22])) & (np.isnan(reformat[:, 23])), 22] / 100
reformat[(~np.isnan(reformat[:, 23])) & (np.isnan(reformat[:, 22])), 22] = reformat[(~np.isnan(reformat[:, 23])) & (np.isnan(reformat[:, 22])), 23] * 100

print('Full ICU -- Doing sample and hold')
sample_and_hold = pd.read_csv('ReferenceFiles/sample_and_hold.csv', index_col = None)

reformatsah = SAH(reformat,sample_and_hold)  # Do SAH first to handle this task

# NO FiO2, YES O2 flow, no interface OR cannula
ii = np.where((np.isnan(reformatsah[:, 22])) & (~np.isnan(reformatsah[:, 24])) & ((reformatsah[:, 21] == 0) | (reformatsah[:, 21] == 2)))[0] #As np.where returns a tuple
reformat[ii[reformatsah[ii, 24] <= 15], 22] = 70
reformat[ii[reformatsah[ii, 24] <= 12], 22] = 62
reformat[ii[reformatsah[ii, 24] <= 10], 22] = 55
reformat[ii[reformatsah[ii, 24] <= 8], 22]  = 50
reformat[ii[reformatsah[ii, 24] <= 6], 22]  = 44
reformat[ii[reformatsah[ii, 24] <= 5], 22]  = 40
reformat[ii[reformatsah[ii, 24] <= 4], 22]  = 36
reformat[ii[reformatsah[ii, 24] <= 3], 22]  = 32
reformat[ii[reformatsah[ii, 24] <= 2], 22]  = 28
reformat[ii[reformatsah[ii, 24] <= 1], 22]  = 24

# NO FiO2, NO O2 flow, no interface OR cannula
ii = np.where((np.isnan(reformatsah[:, 22])) & np.isnan(reformatsah[:, 24]) & ((reformatsah[:, 21] == 0) | (reformatsah[:, 21] == 2)))[0]  #no fio2 given and o2flow given, no interface OR cannula
reformat[ii, 22] = 21

# NO FiO2, YES O2 flow, face mask OR.... OR ventilator (assume it's face mask)
ii = np.where((np.isnan(reformatsah[:, 22])) & (~np.isnan(reformatsah[:, 24])) & 
((reformatsah[:, 21] == 1) | (reformatsah[:, 21]==3) | (reformatsah[:, 21] == 4) | (reformatsah[:, 21] == 5) | (reformatsah[:, 21]==6) | (reformatsah[:, 21]==9) | (reformatsah[:, 21]==10)))[0]
reformat[ii[reformatsah[ii, 24]<=15], 22] = 75
reformat[ii[reformatsah[ii, 24]<=12], 22] = 69
reformat[ii[reformatsah[ii, 24]<=10], 22] = 66
reformat[ii[reformatsah[ii, 24]<=8], 22]  = 58
reformat[ii[reformatsah[ii, 24]<=6], 22]  = 40
reformat[ii[reformatsah[ii, 24]<=4], 22]  = 36

# NO FiO2, NO O2 flow, face mask OR ....OR ventilator
ii = np.where(np.isnan(reformatsah[:, 22]) & np.isnan(reformatsah[:, 24]) & ((reformatsah[:, 21] == 1) | (reformatsah[:, 21] == 3) | 
(reformatsah[:, 21] == 4) | (reformatsah[:, 21] == 5) | (reformatsah[:, 21] == 6) | (reformatsah[:, 21] == 9) | (reformatsah[:, 21] == 10)))[0]  #no fio2 given and o2flow given, no interface OR cannula
reformat[ii, 22] = np.nan

# NO FiO2, YES O2 flow, Non rebreather mask
ii = np.where(np.isnan(reformatsah[:, 22]) & (~np.isnan(reformatsah[:, 24])) & (reformatsah[:, 21] == 7))[0]
reformat[ii[reformatsah[ii, 24] >= 10], 22] = 90
reformat[ii[reformatsah[ii, 24] >= 15], 22] = 100
reformat[ii[reformatsah[ii, 24] < 10], 22]  = 80
reformat[ii[reformatsah[ii, 24] <= 8], 22]  = 70
reformat[ii[reformatsah[ii, 24] <= 6], 22]  = 60

# NO FiO2, NO O2 flow, NRM
ii= np.where(np.isnan(reformatsah[:, 22]) & np.isnan(reformatsah[:, 24]) & (reformatsah[:, 21]==7))[0]  #no fio2 given and o2flow given, no interface OR cannula
reformat[ii, 22] = np.nan

# Update FiO2 columns again
ii = (~np.isnan(reformat[:, 22])) & (np.isnan(reformat[:,23]))
reformat[ii, 23] = reformat[ii, 22]/100
ii = (~np.isnan(reformat[:, 23])) & (np.isnan(reformat[:, 22]))
reformat[ii, 22] = reformat[ii, 23]*100

# Blood Pressure
ii = (~np.isnan(reformat[:, 8])) & (~np.isnan(reformat[:, 9])) & np.isnan(reformat[:, 10])
reformat[ii, 10] = (3*reformat[ii, 9] - reformat[ii, 8])/2
ii = (~np.isnan(reformat[:, 8])) & (~np.isnan(reformat[:, 10])) & np.isnan(reformat[:, 9])
reformat[ii, 9] = (reformat[ii, 8] + 2*reformat[ii, 10])/3
ii = (~np.isnan(reformat[:, 9])) & (~np.isnan(reformat[:, 10])) & np.isnan(reformat[:, 8])
reformat[ii, 8] = 3*reformat[ii, 9] - 2*reformat[ii, 10]

# Temperature
# Some values recorded in the wrong column
ii = (reformat[:, 14] > 25) & (reformat[:, 14] < 45) # tempF close to 37deg??!
reformat[ii, 13] = reformat[ii, 14]
reformat[ii, 14] = np.nan
ii = reformat[:, 13] >70  # tempC > 70, likely recorded in Farenheit
reformat[ii, 14] = reformat[ii, 13]
reformat[ii, 13] = np.nan
ii = (~np.isnan(reformat[:, 13])) & np.isnan(reformat[:, 14])
reformat[ii, 14] = reformat[ii, 13]*1.8+32
ii = (~np.isnan(reformat[:, 14])) & np.isnan(reformat[:, 13])
reformat[ii, 13] = (reformat[ii, 14] - 32)/1.8

# Hb/Ht
ii = (~np.isnan(reformat[:,49])) & np.isnan(reformat[:, 50])
reformat[ii, 50] = (reformat[ii, 49] * 2.862) + 1.216
ii = (~np.isnan(reformat[:, 50])) & np.isnan(reformat[:, 49])
reformat[ii, 49] = (reformat[ii, 50] - 1.216)/2.862

# Bilirubin
ii = (~np.isnan(reformat[:, 43])) & np.isnan(reformat[:, 44])
reformat[ii, 44] = (reformat[ii, 43]*0.6934)-0.1752
ii = (~np.isnan(reformat[:, 44])) & np.isnan(reformat[:, 43])
reformat[ii, 43] = (reformat[ii, 44] + 0.1752)/0.6934

Full ICU -- Doing sample and hold
Warning: No valid output stream.

In [38]:
print('Full ICU -- SAMPLE AND HOLD on RAW DATA')
reformat = SAH(reformat[:,0:68],sample_and_hold)

Full ICU -- SAMPLE AND HOLD on RAW DATA
Warning: No valid output stream.

In [39]:
print(reformat.shape)

(1677195, 68)

In [40]:
print('Full ICU -- Data combination')
# WARNING: the time window of interest has been defined above (here -24 -> +48)! 
timestep = 4  # Resolution of timesteps, in hours
irow = 0   
icustayidlist = np.unique(reformat[:,1]).astype(np.int32)
reformat2 = np.nan*np.ones((reformat.shape[0], 85))  # Output array  
num_patients = len(icustayidlist)  # Number of patients
# Adding 2 empty cols for future shock index=HR/SBP and P/F
reformat = np.hstack([reformat, np.nan*np.ones((reformat.shape[0], 2))])
bar = pyprind.ProgBar(num_patients)
for i in range(len(icustayidlist)):
    bar.update()
    icustayid = icustayidlist[i] 
    
    #CHARTEVENTS AND LAB VALUES
    temp = reformat[reformat[:,1] == icustayid,:]   # subtable of interest
    beg = temp[0,2]   # timestamp of first record
    
    #IV FLUID STUFF
    iv = inputMV['icustay_id'] == icustayid         # rows of interest in inputMV
    input = inputMV[iv]                             # subset of interest
    iv = inputCV['icustay_id'] == icustayid         # rows of interest in inputCV
    input2 = inputCV[iv]                            # subset of interest
    startt = input['starttime']                     # start of all infusions and boluses
    endt = input['endtime']                         # end of all infusions and boluses
    rate = input['norm_rate_of_infusion']           # rate of infusion (is NaN for boluses) || corrected for tonicity
    pread = inputpreadm[inputpreadm['icustay_id'] == icustayid]['inputpreadm'] # preadmission volume

    input = input.values
    input2 = input2.values

    if len(pread) >0:  # store the value, if available
        totvol = np.nansum(pread)
    else:
        totvol=0   # if not documented: it's zero
       
    # Compute volume of fluid given before start of record!!!
    t0 = 0
    t1 = beg
    # Input from MetaVision (4 ways to compute)
    infu = np.nansum(rate*(endt-startt)*((endt<=t1) & (startt >= t0))/3600 + rate*(endt-t0)*((startt <= t0) & (endt <= t1) & (endt >= t0))/3600 +
                            rate*(t1-startt)*((startt >= t0) & (endt >=t1) & (startt <= t1))/3600 + rate*(t1-t0)*((endt >= t1) & (startt <= t0))/3600)
    # All boluses received during this timestep, from inputMV (need to check rate is NaN) and inputCV (simpler):
    bolus = np.nansum(input[np.isnan(input[:, 5]) & (input[:, 1] >= t0) & (input[:, 1] <= t1), 6]) + np.nansum(input2[(input2[:, 1] >= t0) & (input2[:, 1] <= t1), 4])
    totvol = np.nansum([totvol,infu,bolus]) 
    
    #########################################################################################
    #VASOPRESSORS    
    iv = vasoMV['icustay_id'] == icustayid  # rows of interest in vasoMV
    vaso1 = vasoMV[iv]    # subset of interest
    iv = vasoCV['icustay_id'] == icustayid   # rows of interest in vasoCV
    vaso2 = vasoCV[iv]    # subset of interest
    startv = vaso1['starttime'].values  # start of VP infusion
    endv = vaso1['endtime'].values      # end of VP infusions
    ratev = vaso1['rate_std'].values  # rate of VP infusion
    
    # DEMOGRAPHICS / gender, age, elixhauser, re-admit, died in hosp?, died within
    # 48h of out_time (likely in ICU or soon after), died within 90d after admission?        
    demogi = demog['icustay_id'] == icustayid
    dem = np.array(
            list(demog.gender[demogi].values) +
            list(demog.age[demogi].values) +
            list(demog.elixhauser[demogi].values) +
            list(demog.re_admission[demogi].values) + 
            list(demog.morta_hosp[demogi].values) + 
            list(abs(demog.dod[demogi].values - demog.outtime[demogi].values) < (24*3600*2)) +
            list(demog.morta_90[demogi].values) + 
            [(qstime[icustayid][3] - qstime[icustayid][2])/3600]
            )
        
        
    #URINE OUTPUT
    iu = UO['icustay_id'] == icustayid   #rows of interest in inputMV
    output = UO[iu]    #subset of interest
    pread = UOpreadm[UOpreadm['icustay_id'] == icustayid-200000]['value'].values #preadmission UO ????????????????? Why no + 200000 for icustayid here?
    if len(pread) > 0:     #store the value, if available
        UOtot = np.nansum(pread)
    else:
        UOtot = 0
    #adding the volume of urine produced before start of recording!    
    UOnow = np.nansum(output[(output['charttime']>=t0) & (output['charttime'] <= t1)]['value'].values) #t0 and t1 defined above
    UOtot = np.nansum([UOtot, UOnow])
    
    
    for j in range(0, 79, timestep): #0:timestep:79 #-28 until +52 = 80 hours in total
        t0 = 3600*j + beg   #left limit of time window
        t1 = 3600*(j + timestep) + beg   #right limit of time window
        ii = (temp[:, 2] >= t0) & (temp[:, 2] <= t1)  #index of items in this time period
        if sum(ii)>0:
            #ICUSTAY_ID, OUTCOMES, DEMOGRAPHICS
            reformat2[irow, 0] = (j/timestep)+1    # 'bloc' = timestep (1,2,3...)
            reformat2[irow, 1] = icustayid         # icustay_ID
            reformat2[irow, 2] = 3600*j+ beg       # t0 = lower limit of time window
            reformat2[irow, 3:11] = dem            # demographics and outcomes
            
            #CHARTEVENTS and LAB VALUES (+ includes empty cols for shock index and P/F)
            value = temp[ii]  # Records all values in this timestep
                
            if sum(ii) == 1:   # if only 1 row of values at this timestep
                reformat2[irow, 11:78] = value[:, 3:]
            else:
                reformat2[irow, 11:78] = np.nanmean(value[:, 3:], axis=0)  # mean of all available values
        
            # VASOPRESSORS
            # for CV: dose at timestamps.
            # for MV: 4 possibles cases, each one needing a different way to compute the dose of VP actually administered:
            #----t0---start----end-----t1----
            #----start---t0----end----t1----
            #-----t0---start---t1---end
            #----start---t0----t1---end----
            # MetaVision
            v = ((endv >= t0) & (endv <= t1)) | ((startv >= t0) & (endv<=t1)) | ((startv >= t0) & (startv <= t1))| ((startv <= t0) & (endv>=t1))
            # CareVue
            v2 = vaso2[(vaso2['charttime'] >= t0) & (vaso2['charttime'] <= t1)]['rate_std'].values
            if len(list(ratev[v]) +  list(v2)) > 0:
                v1 = np.nanmedian(list(ratev[v]) +  list(v2))
                v2 = np.nanmax(list(ratev[v]) + list(v2))
            else:
                v1 = np.nan
                v2 = np.nan
            
            if (~np.isnan(v1)) and (~np.isnan(v2)):
                reformat2[irow, 78] = v1    #median of dose of VP
                reformat2[irow, 79] = v2    #max dose of VP
        
            # INPUT FLUID
            # Input from MV (4 ways to compute)
            infu = np.nansum(rate*(endt-startt)*((endt <= t1) & (startt >= t0))/3600 
                                          + rate*(endt-t0)*((startt <= t0) & (endt <= t1) & (endt >= t0))/3600 
                                          + rate*(t1-startt)*((startt >= t0) & (endt >= t1) & (startt <= t1))/3600 
                                          + rate*(t1-t0)*((endt >=t1) & (startt <= t0))/3600)
            # All boluses received during this timestep, from inputMV (need to check rate is NaN) and inputCV (simpler):
            bolus = np.nansum(input[(np.isnan(input[:, 5])) & (input[:, 1] >= t0) & (input[:, 1] <= t1), 6]) + np.nansum(input2[(input2[:, 1] >= t0) & (input2[:, 1] <= t1), 4])
            # Cumulate all fluid given
            totvol = np.nansum([totvol, infu, bolus])
            reformat2[irow, 80] = totvol    #total fluid given
            reformat2[irow, 81] = np.nansum([infu, bolus])  #fluid given at this step
            
            # Urine Output
            UOnow = np.nansum(output[(output['charttime'] >= t0) & (output['charttime'] <= t1)]['value'].values)
            UOtot = np.nansum([UOtot, UOnow])
            reformat2[irow, 82] = UOtot    # Total Urine Output
            reformat2[irow, 83] = np.nansum(UOnow)  # Urine Output at this step

            #CUMULATED BALANCE
            reformat2[irow, 84] = totvol - UOtot

            irow += 1

reformat2 = np.delete(reformat2, range(irow, len(reformat2)) ,axis=0)

Full ICU -- Data combination
Warning: No valid output stream.

/var/folders/c9/gz43vn156vs2b_jhrbcnkdnh0000gn/T/ipykernel_2532/4247654529.py:102: RuntimeWarning: Mean of empty slice
  reformat2[irow, 11:78] = np.nanmean(value[:, 3:], axis=0)  # mean of all available values

In [41]:
print('FULL ICU -- CONVERTING TO TABLE AND DELETE VARIABLES WITH EXCESSIVE MISSINGNESS')
dataheaders = ['Height_cm', 'Weight_kg', 'GCS','RASS','HR', 'SysBP', 'MeanBP', 'DiaBP',	'RR', 'SpO2', 'Temp_C', 'Temp_F', 'CVP', 'PAPsys', 'PAPmean', 'PAPdia', 'CI', 
'SVR', 'Interface', 'FiO2_100', 'FiO2_1', 'O2flow', 'PEEP', 'TidalVolume', 'MinuteVentil', 'PAWmean', 'PAWpeak', 'PAWplateau', 'Potassium', 'Sodium',
'Chloride', 'Glucose', 'BUN', 'Creatinine', 'Magnesium', 'Calcium', 'Ionised_Ca', 'CO2_mEqL', 'SGOT', 'SGPT', 'Total_bili', 'Direct_bili', 'Total_protein',
'Albumin', 'Troponin', 'CRP', 'Hb', 'Ht', 'RBC_count', 'WBC_count', 'Platelets_count', 'PTT', 'PT', 'ACT', 'INR', 'Arterial_pH', 'paO2', 'paCO2',
'Arterial_BE', 'Arterial_lactate', 'HCO3', 'ETCO2', 'SvO2', 'mechvent', 'extubated', 'Shock_Index', 'PaO2_FiO2']
dataheaders = ['bloc','icustayid','charttime','gender','age','elixhauser','re_admission', 'died_in_hosp', 'died_within_48h_of_out_time','mortality_90d','delay_end_of_record_and_discharge_or_death'] + \
    dataheaders + ['median_dose_vaso','max_dose_vaso','input_total','input_4hourly','output_total','output_4hourly','cumulated_balance']

reformat2t = pd.DataFrame(reformat2, columns=dataheaders)
miss = np.sum(np.isnan(reformat2), axis=0)/reformat2.shape[0]

# If values have less than 70% missing values (over 30% of values present): I keep them
reformat3 = reformat2[:,[True]*11 + (miss[11:74] < 0.7).tolist() + [True]*11]
reformat3t = pd.DataFrame(reformat3, columns= reformat2t.columns[[True]*11 + (miss[11:74] < 0.7).tolist() + [True]*11])

FULL ICU -- CONVERTING TO TABLE AND DELETE VARIABLES WITH EXCESSIVE MISSINGNESS

In [42]:
# Do linear interpolation where missingness is low (kNN imputation doesnt work if all rows have missing values)
print('Full ICU -- Doing linear interpolation where missingness is low (kNN imputation doesnt work if all rows have missing values)')
miss = np.sum(np.isnan(reformat3), axis=0)/reformat3.shape[0]
ii = (miss>0) & (miss<0.05)  #less than 5% missingness
mechventcol = reformat3t.columns.tolist().index('mechvent')

for i in range(10,mechventcol): # Correct column by column
    if ii[i]==1:
        reformat3[:,i] = fixgaps(reformat3[:,i])

reformat3t[reformat3t.columns[10:mechventcol]] = reformat3[:,10:mechventcol]

# KNN IMPUTATION -  Done on chunks of 10K records.
print('Full ICU -- KNN imputation')

reformat3t_cols = reformat3t.columns.tolist()
mechventcol = reformat3t_cols.index('mechvent')
ref = np.copy(reformat3[:,11:mechventcol])  #columns of interest

bar_knn = pyprind.ProgBar(len(range(0,reformat3.shape[0],9999)))
for i in range(0,reformat3.shape[0],9999):   #dataset divided in 10K rows chunks (otherwise too large)
    bar_knn.update()
    ref[i:i+9999,:] = KNN(k=1).fit_transform(ref[i:i+9999,:])

reformat3t[reformat3t_cols[11:mechventcol]] = ref 

reformat4t = reformat3t.copy()
reformat4 = reformat4t.values

Full ICU -- Doing linear interpolation where missingness is low (kNN imputation doesnt work if all rows have missing values)
Full ICU -- KNN imputation
Warning: No valid output stream.
Imputing row 1/9999 with 24 missing, elapsed time: 16.989
Imputing row 101/9999 with 10 missing, elapsed time: 17.046
Imputing row 201/9999 with 19 missing, elapsed time: 17.094
Imputing row 301/9999 with 9 missing, elapsed time: 17.154
Imputing row 401/9999 with 15 missing, elapsed time: 17.218
Imputing row 501/9999 with 15 missing, elapsed time: 17.285
Imputing row 601/9999 with 4 missing, elapsed time: 17.348
Imputing row 701/9999 with 36 missing, elapsed time: 17.412
Imputing row 801/9999 with 7 missing, elapsed time: 17.470
Imputing row 901/9999 with 15 missing, elapsed time: 17.518
Imputing row 1001/9999 with 20 missing, elapsed time: 17.589
Imputing row 1101/9999 with 8 missing, elapsed time: 17.649
Imputing row 1201/9999 with 12 missing, elapsed time: 17.709
Imputing row 1301/9999 with 10 missing, elapsed time: 17.779
Imputing row 1401/9999 with 1 missing, elapsed time: 17.833
Imputing row 1501/9999 with 30 missing, elapsed time: 17.893
Imputing row 1601/9999 with 14 missing, elapsed time: 17.966
Imputing row 1701/9999 with 15 missing, elapsed time: 18.037
Imputing row 1801/9999 with 18 missing, elapsed time: 18.099
Imputing row 1901/9999 with 31 missing, elapsed time: 18.164
Imputing row 2001/9999 with 13 missing, elapsed time: 18.227
Imputing row 2101/9999 with 16 missing, elapsed time: 18.286
Imputing row 2201/9999 with 4 missing, elapsed time: 18.416
Imputing row 2301/9999 with 1 missing, elapsed time: 18.518
Imputing row 2401/9999 with 8 missing, elapsed time: 18.577
Imputing row 2501/9999 with 13 missing, elapsed time: 18.643
Imputing row 2601/9999 with 13 missing, elapsed time: 18.715
Imputing row 2701/9999 with 11 missing, elapsed time: 18.780
Imputing row 2801/9999 with 16 missing, elapsed time: 18.847
Imputing row 2901/9999 with 13 missing, elapsed time: 18.919
Imputing row 3001/9999 with 3 missing, elapsed time: 18.990
Imputing row 3101/9999 with 9 missing, elapsed time: 19.052
Imputing row 3201/9999 with 10 missing, elapsed time: 19.115
Imputing row 3301/9999 with 4 missing, elapsed time: 19.176
Imputing row 3401/9999 with 12 missing, elapsed time: 19.235
Imputing row 3501/9999 with 18 missing, elapsed time: 19.295
Imputing row 3601/9999 with 11 missing, elapsed time: 19.357
Imputing row 3701/9999 with 14 missing, elapsed time: 19.416
Imputing row 3801/9999 with 12 missing, elapsed time: 19.484
Imputing row 3901/9999 with 21 missing, elapsed time: 19.526
Imputing row 4001/9999 with 21 missing, elapsed time: 19.593
Imputing row 4101/9999 with 31 missing, elapsed time: 19.647
Imputing row 4201/9999 with 10 missing, elapsed time: 19.706
Imputing row 4301/9999 with 13 missing, elapsed time: 19.760
Imputing row 4401/9999 with 5 missing, elapsed time: 19.821
Imputing row 4501/9999 with 20 missing, elapsed time: 19.892
Imputing row 4601/9999 with 11 missing, elapsed time: 19.949
Imputing row 4701/9999 with 16 missing, elapsed time: 20.002
Imputing row 4801/9999 with 26 missing, elapsed time: 20.071
Imputing row 4901/9999 with 14 missing, elapsed time: 20.162
Imputing row 5001/9999 with 16 missing, elapsed time: 20.209
Imputing row 5101/9999 with 17 missing, elapsed time: 20.289
Imputing row 5201/9999 with 14 missing, elapsed time: 20.354
Imputing row 5301/9999 with 22 missing, elapsed time: 20.398
Imputing row 5401/9999 with 3 missing, elapsed time: 20.459
Imputing row 5501/9999 with 19 missing, elapsed time: 20.518
Imputing row 5601/9999 with 2 missing, elapsed time: 20.575
Imputing row 5701/9999 with 22 missing, elapsed time: 20.635
Imputing row 5801/9999 with 12 missing, elapsed time: 20.702
Imputing row 5901/9999 with 13 missing, elapsed time: 20.773
Imputing row 6001/9999 with 17 missing, elapsed time: 20.840
Imputing row 6101/9999 with 18 missing, elapsed time: 20.898
Imputing row 6201/9999 with 10 missing, elapsed time: 20.968
Imputing row 6301/9999 with 12 missing, elapsed time: 21.028
Imputing row 6401/9999 with 6 missing, elapsed time: 21.086
Imputing row 6501/9999 with 23 missing, elapsed time: 21.132
Imputing row 6601/9999 with 10 missing, elapsed time: 21.190
Imputing row 6701/9999 with 15 missing, elapsed time: 21.250
Imputing row 6801/9999 with 11 missing, elapsed time: 21.311
Imputing row 6901/9999 with 28 missing, elapsed time: 21.376
Imputing row 7001/9999 with 7 missing, elapsed time: 21.436
Imputing row 7101/9999 with 20 missing, elapsed time: 21.495
Imputing row 7201/9999 with 12 missing, elapsed time: 21.562
Imputing row 7301/9999 with 11 missing, elapsed time: 21.626
Imputing row 7401/9999 with 11 missing, elapsed time: 21.695
Imputing row 7501/9999 with 9 missing, elapsed time: 21.757
Imputing row 7601/9999 with 18 missing, elapsed time: 21.821
Imputing row 7701/9999 with 16 missing, elapsed time: 21.887
Imputing row 7801/9999 with 3 missing, elapsed time: 21.947
Imputing row 7901/9999 with 20 missing, elapsed time: 22.015
Imputing row 8001/9999 with 9 missing, elapsed time: 22.066
Imputing row 8101/9999 with 6 missing, elapsed time: 22.142
Imputing row 8201/9999 with 32 missing, elapsed time: 22.207
Imputing row 8301/9999 with 5 missing, elapsed time: 22.265
Imputing row 8401/9999 with 31 missing, elapsed time: 22.327
Imputing row 8501/9999 with 29 missing, elapsed time: 22.389
Imputing row 8601/9999 with 1 missing, elapsed time: 22.445
Imputing row 8701/9999 with 16 missing, elapsed time: 22.506
Imputing row 8801/9999 with 10 missing, elapsed time: 22.561
Imputing row 8901/9999 with 15 missing, elapsed time: 22.623
Imputing row 9001/9999 with 7 missing, elapsed time: 22.693
Imputing row 9101/9999 with 14 missing, elapsed time: 22.761
Imputing row 9201/9999 with 19 missing, elapsed time: 22.834
Imputing row 9301/9999 with 25 missing, elapsed time: 22.904
Imputing row 9401/9999 with 6 missing, elapsed time: 22.967
Imputing row 9501/9999 with 26 missing, elapsed time: 23.026
Imputing row 9601/9999 with 25 missing, elapsed time: 23.104
Imputing row 9701/9999 with 5 missing, elapsed time: 23.164
Imputing row 9801/9999 with 8 missing, elapsed time: 23.220
Imputing row 9901/9999 with 14 missing, elapsed time: 23.276
Imputing row 1/9999 with 27 missing, elapsed time: 16.455
Imputing row 101/9999 with 5 missing, elapsed time: 16.518
Imputing row 201/9999 with 16 missing, elapsed time: 16.568
Imputing row 301/9999 with 21 missing, elapsed time: 16.637
Imputing row 401/9999 with 4 missing, elapsed time: 16.679
Imputing row 501/9999 with 16 missing, elapsed time: 16.747
Imputing row 601/9999 with 8 missing, elapsed time: 16.797
Imputing row 701/9999 with 16 missing, elapsed time: 16.847
Imputing row 801/9999 with 5 missing, elapsed time: 16.894
Imputing row 901/9999 with 16 missing, elapsed time: 16.935
Imputing row 1001/9999 with 12 missing, elapsed time: 16.996
Imputing row 1101/9999 with 30 missing, elapsed time: 17.060
Imputing row 1201/9999 with 13 missing, elapsed time: 17.112
Imputing row 1301/9999 with 7 missing, elapsed time: 17.181
Imputing row 1401/9999 with 20 missing, elapsed time: 17.253
Imputing row 1501/9999 with 8 missing, elapsed time: 17.314
Imputing row 1601/9999 with 6 missing, elapsed time: 17.370
Imputing row 1701/9999 with 10 missing, elapsed time: 17.429
Imputing row 1801/9999 with 14 missing, elapsed time: 17.492
Imputing row 1901/9999 with 6 missing, elapsed time: 17.562
Imputing row 2001/9999 with 6 missing, elapsed time: 17.621
Imputing row 2101/9999 with 3 missing, elapsed time: 17.676
Imputing row 2201/9999 with 7 missing, elapsed time: 17.720
Imputing row 2301/9999 with 8 missing, elapsed time: 17.770
Imputing row 2401/9999 with 6 missing, elapsed time: 17.840
Imputing row 2501/9999 with 7 missing, elapsed time: 17.904
Imputing row 2601/9999 with 15 missing, elapsed time: 17.962
Imputing row 2701/9999 with 15 missing, elapsed time: 18.016
Imputing row 2801/9999 with 2 missing, elapsed time: 18.070
Imputing row 2901/9999 with 23 missing, elapsed time: 18.106
Imputing row 3001/9999 with 27 missing, elapsed time: 18.165
Imputing row 3101/9999 with 5 missing, elapsed time: 18.225
Imputing row 3201/9999 with 7 missing, elapsed time: 18.291
Imputing row 3301/9999 with 27 missing, elapsed time: 18.352
Imputing row 3401/9999 with 7 missing, elapsed time: 18.412
Imputing row 3501/9999 with 14 missing, elapsed time: 18.477
Imputing row 3601/9999 with 11 missing, elapsed time: 18.516
Imputing row 3701/9999 with 17 missing, elapsed time: 18.581
Imputing row 3801/9999 with 23 missing, elapsed time: 18.639
Imputing row 3901/9999 with 17 missing, elapsed time: 18.703
Imputing row 4001/9999 with 14 missing, elapsed time: 18.766
Imputing row 4101/9999 with 14 missing, elapsed time: 18.832
Imputing row 4201/9999 with 19 missing, elapsed time: 18.902
Imputing row 4301/9999 with 1 missing, elapsed time: 18.957
Imputing row 4401/9999 with 14 missing, elapsed time: 19.009
Imputing row 4501/9999 with 3 missing, elapsed time: 19.056
Imputing row 4601/9999 with 6 missing, elapsed time: 19.123
Imputing row 4701/9999 with 20 missing, elapsed time: 19.186
Imputing row 4801/9999 with 13 missing, elapsed time: 19.249
Imputing row 4901/9999 with 15 missing, elapsed time: 19.311
Imputing row 5001/9999 with 21 missing, elapsed time: 19.374
Imputing row 5101/9999 with 6 missing, elapsed time: 19.423
Imputing row 5201/9999 with 19 missing, elapsed time: 19.469
Imputing row 5301/9999 with 14 missing, elapsed time: 19.520
Imputing row 5401/9999 with 11 missing, elapsed time: 19.581
Imputing row 5501/9999 with 7 missing, elapsed time: 19.620
Imputing row 5601/9999 with 15 missing, elapsed time: 19.673
Imputing row 5701/9999 with 13 missing, elapsed time: 19.736
Imputing row 5801/9999 with 16 missing, elapsed time: 19.811
Imputing row 5901/9999 with 6 missing, elapsed time: 19.862
Imputing row 6001/9999 with 19 missing, elapsed time: 19.928
Imputing row 6101/9999 with 25 missing, elapsed time: 20.003
Imputing row 6201/9999 with 9 missing, elapsed time: 20.060
Imputing row 6301/9999 with 17 missing, elapsed time: 20.123
Imputing row 6401/9999 with 9 missing, elapsed time: 20.179
Imputing row 6501/9999 with 23 missing, elapsed time: 20.249
Imputing row 6601/9999 with 22 missing, elapsed time: 20.327
Imputing row 6701/9999 with 3 missing, elapsed time: 20.377
Imputing row 6801/9999 with 20 missing, elapsed time: 20.441
Imputing row 6901/9999 with 6 missing, elapsed time: 20.508
Imputing row 7001/9999 with 3 missing, elapsed time: 20.551
Imputing row 7101/9999 with 13 missing, elapsed time: 20.607
Imputing row 7201/9999 with 17 missing, elapsed time: 20.678
Imputing row 7301/9999 with 4 missing, elapsed time: 20.734
Imputing row 7401/9999 with 7 missing, elapsed time: 20.795
Imputing row 7501/9999 with 5 missing, elapsed time: 20.863
Imputing row 7601/9999 with 10 missing, elapsed time: 20.921
Imputing row 7701/9999 with 15 missing, elapsed time: 20.988
Imputing row 7801/9999 with 14 missing, elapsed time: 21.042
Imputing row 7901/9999 with 23 missing, elapsed time: 21.107
Imputing row 8001/9999 with 11 missing, elapsed time: 21.167
Imputing row 8101/9999 with 2 missing, elapsed time: 21.223
Imputing row 8201/9999 with 10 missing, elapsed time: 21.286
Imputing row 8301/9999 with 12 missing, elapsed time: 21.344
Imputing row 8401/9999 with 27 missing, elapsed time: 21.406
Imputing row 8501/9999 with 6 missing, elapsed time: 21.452
Imputing row 8601/9999 with 13 missing, elapsed time: 21.515
Imputing row 8701/9999 with 18 missing, elapsed time: 21.577
Imputing row 8801/9999 with 15 missing, elapsed time: 21.650
Imputing row 8901/9999 with 20 missing, elapsed time: 21.720
Imputing row 9001/9999 with 18 missing, elapsed time: 21.784
Imputing row 9101/9999 with 11 missing, elapsed time: 21.833
Imputing row 9201/9999 with 18 missing, elapsed time: 21.899
Imputing row 9301/9999 with 9 missing, elapsed time: 21.964
Imputing row 9401/9999 with 24 missing, elapsed time: 22.017
Imputing row 9501/9999 with 28 missing, elapsed time: 22.080
Imputing row 9601/9999 with 8 missing, elapsed time: 22.147
Imputing row 9701/9999 with 8 missing, elapsed time: 22.200
Imputing row 9801/9999 with 18 missing, elapsed time: 22.261
Imputing row 9901/9999 with 17 missing, elapsed time: 22.328
Imputing row 1/9999 with 17 missing, elapsed time: 16.464
Imputing row 101/9999 with 6 missing, elapsed time: 16.532
Imputing row 201/9999 with 18 missing, elapsed time: 16.592
Imputing row 301/9999 with 20 missing, elapsed time: 16.655
Imputing row 401/9999 with 12 missing, elapsed time: 16.716
Imputing row 501/9999 with 10 missing, elapsed time: 16.776
Imputing row 601/9999 with 12 missing, elapsed time: 16.843
Imputing row 701/9999 with 2 missing, elapsed time: 16.901
Imputing row 801/9999 with 1 missing, elapsed time: 16.968
Imputing row 901/9999 with 13 missing, elapsed time: 17.028
Imputing row 1001/9999 with 18 missing, elapsed time: 17.094
Imputing row 1101/9999 with 12 missing, elapsed time: 17.170
Imputing row 1201/9999 with 25 missing, elapsed time: 17.244
Imputing row 1301/9999 with 0 missing, elapsed time: 17.301
Imputing row 1401/9999 with 19 missing, elapsed time: 17.356
Imputing row 1501/9999 with 11 missing, elapsed time: 17.428
Imputing row 1601/9999 with 10 missing, elapsed time: 17.496
Imputing row 1701/9999 with 10 missing, elapsed time: 17.568
Imputing row 1801/9999 with 29 missing, elapsed time: 17.625
Imputing row 1901/9999 with 11 missing, elapsed time: 17.682
Imputing row 2001/9999 with 14 missing, elapsed time: 17.737
Imputing row 2101/9999 with 1 missing, elapsed time: 17.802
Imputing row 2201/9999 with 12 missing, elapsed time: 17.867
Imputing row 2301/9999 with 5 missing, elapsed time: 17.937
Imputing row 2401/9999 with 12 missing, elapsed time: 17.995
Imputing row 2501/9999 with 4 missing, elapsed time: 18.066
Imputing row 2601/9999 with 16 missing, elapsed time: 18.121
Imputing row 2701/9999 with 16 missing, elapsed time: 18.182
Imputing row 2801/9999 with 13 missing, elapsed time: 18.245
Imputing row 2901/9999 with 16 missing, elapsed time: 18.303
Imputing row 3001/9999 with 15 missing, elapsed time: 18.363
Imputing row 3101/9999 with 9 missing, elapsed time: 18.435
Imputing row 3201/9999 with 30 missing, elapsed time: 18.493
Imputing row 3301/9999 with 3 missing, elapsed time: 18.545
Imputing row 3401/9999 with 28 missing, elapsed time: 18.605
Imputing row 3501/9999 with 17 missing, elapsed time: 18.666
Imputing row 3601/9999 with 10 missing, elapsed time: 18.725
Imputing row 3701/9999 with 29 missing, elapsed time: 18.788
Imputing row 3801/9999 with 5 missing, elapsed time: 18.856
Imputing row 3901/9999 with 13 missing, elapsed time: 18.912
Imputing row 4001/9999 with 10 missing, elapsed time: 18.970
Imputing row 4101/9999 with 4 missing, elapsed time: 19.023
Imputing row 4201/9999 with 13 missing, elapsed time: 19.074
Imputing row 4301/9999 with 25 missing, elapsed time: 19.136
Imputing row 4401/9999 with 9 missing, elapsed time: 19.188
Imputing row 4501/9999 with 22 missing, elapsed time: 19.249
Imputing row 4601/9999 with 4 missing, elapsed time: 19.301
Imputing row 4701/9999 with 13 missing, elapsed time: 19.366
Imputing row 4801/9999 with 17 missing, elapsed time: 19.427
Imputing row 4901/9999 with 11 missing, elapsed time: 19.477
Imputing row 5001/9999 with 9 missing, elapsed time: 19.529
Imputing row 5101/9999 with 9 missing, elapsed time: 19.597
Imputing row 5201/9999 with 15 missing, elapsed time: 19.654
Imputing row 5301/9999 with 18 missing, elapsed time: 19.710
Imputing row 5401/9999 with 14 missing, elapsed time: 19.763
Imputing row 5501/9999 with 19 missing, elapsed time: 19.831
Imputing row 5601/9999 with 18 missing, elapsed time: 19.889
Imputing row 5701/9999 with 22 missing, elapsed time: 19.954
Imputing row 5801/9999 with 2 missing, elapsed time: 20.026
Imputing row 5901/9999 with 8 missing, elapsed time: 20.071
Imputing row 6001/9999 with 20 missing, elapsed time: 20.132
Imputing row 6101/9999 with 23 missing, elapsed time: 20.182
Imputing row 6201/9999 with 11 missing, elapsed time: 20.243
Imputing row 6301/9999 with 1 missing, elapsed time: 20.306
Imputing row 6401/9999 with 10 missing, elapsed time: 20.367
Imputing row 6501/9999 with 12 missing, elapsed time: 20.416
Imputing row 6601/9999 with 17 missing, elapsed time: 20.472
Imputing row 6701/9999 with 12 missing, elapsed time: 20.531
Imputing row 6801/9999 with 5 missing, elapsed time: 20.581
Imputing row 6901/9999 with 6 missing, elapsed time: 20.646
Imputing row 7001/9999 with 9 missing, elapsed time: 20.710
Imputing row 7101/9999 with 20 missing, elapsed time: 20.767
Imputing row 7201/9999 with 15 missing, elapsed time: 20.827
Imputing row 7301/9999 with 21 missing, elapsed time: 20.876
Imputing row 7401/9999 with 4 missing, elapsed time: 20.941
Imputing row 7501/9999 with 3 missing, elapsed time: 21.004
Imputing row 7601/9999 with 16 missing, elapsed time: 21.059
Imputing row 7701/9999 with 14 missing, elapsed time: 21.121
Imputing row 7801/9999 with 8 missing, elapsed time: 21.169
Imputing row 7901/9999 with 26 missing, elapsed time: 21.206
Imputing row 8001/9999 with 9 missing, elapsed time: 21.257
Imputing row 8101/9999 with 6 missing, elapsed time: 21.309
Imputing row 8201/9999 with 11 missing, elapsed time: 21.365
Imputing row 8301/9999 with 4 missing, elapsed time: 21.421
Imputing row 8401/9999 with 27 missing, elapsed time: 21.489
Imputing row 8501/9999 with 11 missing, elapsed time: 21.543
Imputing row 8601/9999 with 10 missing, elapsed time: 21.591
Imputing row 8701/9999 with 29 missing, elapsed time: 21.653
Imputing row 8801/9999 with 7 missing, elapsed time: 21.718
Imputing row 8901/9999 with 10 missing, elapsed time: 21.786
Imputing row 9001/9999 with 3 missing, elapsed time: 21.835
Imputing row 9101/9999 with 13 missing, elapsed time: 21.893
Imputing row 9201/9999 with 1 missing, elapsed time: 21.947
Imputing row 9301/9999 with 21 missing, elapsed time: 22.002
Imputing row 9401/9999 with 9 missing, elapsed time: 22.059
Imputing row 9501/9999 with 17 missing, elapsed time: 22.122
Imputing row 9601/9999 with 4 missing, elapsed time: 22.177
Imputing row 9701/9999 with 2 missing, elapsed time: 22.227
Imputing row 9801/9999 with 13 missing, elapsed time: 22.288
Imputing row 9901/9999 with 3 missing, elapsed time: 22.346
Imputing row 1/9999 with 13 missing, elapsed time: 16.522
Imputing row 101/9999 with 9 missing, elapsed time: 16.583
Imputing row 201/9999 with 15 missing, elapsed time: 16.646
Imputing row 301/9999 with 29 missing, elapsed time: 16.715
Imputing row 401/9999 with 10 missing, elapsed time: 16.771
Imputing row 501/9999 with 3 missing, elapsed time: 16.826
Imputing row 601/9999 with 15 missing, elapsed time: 16.896
Imputing row 701/9999 with 34 missing, elapsed time: 16.964
Imputing row 801/9999 with 16 missing, elapsed time: 17.027
Imputing row 901/9999 with 14 missing, elapsed time: 17.081
Imputing row 1001/9999 with 20 missing, elapsed time: 17.147
Imputing row 1101/9999 with 17 missing, elapsed time: 17.201
Imputing row 1201/9999 with 21 missing, elapsed time: 17.270
Imputing row 1301/9999 with 2 missing, elapsed time: 17.325
Imputing row 1401/9999 with 14 missing, elapsed time: 17.385
Imputing row 1501/9999 with 9 missing, elapsed time: 17.461
Imputing row 1601/9999 with 19 missing, elapsed time: 17.517
Imputing row 1701/9999 with 15 missing, elapsed time: 17.578
Imputing row 1801/9999 with 11 missing, elapsed time: 17.654
Imputing row 1901/9999 with 16 missing, elapsed time: 17.727
Imputing row 2001/9999 with 26 missing, elapsed time: 17.795
Imputing row 2101/9999 with 11 missing, elapsed time: 17.867
Imputing row 2201/9999 with 16 missing, elapsed time: 17.929
Imputing row 2301/9999 with 5 missing, elapsed time: 17.989
Imputing row 2401/9999 with 14 missing, elapsed time: 18.042
Imputing row 2501/9999 with 11 missing, elapsed time: 18.108
Imputing row 2601/9999 with 13 missing, elapsed time: 18.148

In [43]:
print('FULL ICU -- COMPUTING SOME DERIVED VARIABLES: P/F, Shock Index, SOFA, SIRS...')
# CORRECT GENDER
reformat4t['gender'] = reformat4t['gender'] - 1

# CORRECT AGE > 200 yo
ii = reformat4t['age'] > 150*365.25
reformat4t.loc[ii,'age'] = 91.4*365.25

# FIX MECHVENT
reformat4t['mechvent'].fillna(0, inplace=True)
reformat4t.loc[reformat4t['mechvent'] > 0, 'mechvent'] = 1

# FIX Elixhauser missing values
reformat4t['elixhauser'].loc[np.isnan(reformat4t['elixhauser'])] = np.nanmedian(reformat4t['elixhauser'])   #use the median value / only a few missing data points 

# Vasopressors / no NAN
reformat4t['median_dose_vaso'].fillna(0, inplace=True)
reformat4t['max_dose_vaso'].fillna(0, inplace=True)

# Recompute P/F with no missing values...
reformat4t['PaO2_FiO2'] = reformat4t['paO2']/reformat4t['FiO2_1']

# Recompute SHOCK INDEX without NAN and INF
reformat4t['Shock_Index'] = reformat4t['HR']/reformat4t['SysBP']

reformat4t.loc[np.isinf(reformat4t['Shock_Index']), 'Shock_Index'] = np.NaN

d = np.nanmean(reformat4t['Shock_Index'])
reformat4t['Shock_Index'].fillna(d, inplace=True)

# SOFA - at each timepoint we need (in this order):  
# P/F,  MV,  PLT,  TOT_BILI,  MAP,  NORAD(max),  GCS,  CR,  UO
s = reformat4t[['PaO2_FiO2', 'Platelets_count', 'Total_bili', 'MeanBP', 'max_dose_vaso', 'GCS', 'Creatinine', 'output_4hourly']].values
p = np.arange(5)
s1=np.array([s[:,0]>400, (s[:, 0]>=300) & (s[:, 0]<400), (s[:, 0]>=200) & (s[:, 0]<300), (s[:, 0]>=100) & (s[:, 0]<200), s[:, 0]<100 ])   #count of points for all 6 criteria of sofa
s2=np.array([s[:,1]>150, (s[:, 1]>=100) & (s[:, 1]<150), (s[:, 1]>=50) & (s[:, 1]<100), (s[:, 1]>=20) & (s[:, 1]<50), s[:, 1]<20 ])
s3=np.array([s[:, 2]<1.2, (s[:, 2]>=1.2) & (s[:, 2]<2), (s[:, 2]>=2) & (s[:, 2]<6), (s[:, 2]>=6) & (s[:, 2]<12), s[:, 2]>12 ])
s4=np.array([s[:, 3]>=70, (s[:, 3]<70) & (s[:, 3]>=65), (s[:, 3]<65), (s[:, 4]>0) & (s[:, 4]<=0.1), s[:, 4]>0.1 ])
s5=np.array([s[:, 5]>14, (s[:, 5]>12) & (s[:, 5]<=14), (s[:, 5]>9) & (s[:, 5]<=12), (s[:, 5]>5) & (s[:, 5]<=9), s[:, 5]<=5])
s6=np.array([s[:, 6]<1.2, (s[:, 6]>=1.2) & (s[:, 6]<2), (s[:, 6]>=2) & (s[:, 6]<3.5), ((s[:, 6]>=3.5) & (s[:, 6]<5))|(s[:, 7]<84), (s[:, 6]>5)|(s[:, 7]<34)])

num_columns = reformat4t.shape[1]   #nr of variables in data
newcols_reformat4 = np.zeros((reformat4t.shape[0],7)) 
for i in range(reformat4t.shape[0]):
    t = max(p[s1[:, i]], default=0) + max(p[s2[:, i]], default=0) + max(p[s3[:, i]], default=0) + max(p[s4[:, i]], default=0) + max(p[s5[:, i]], default=0) + max(p[s6[:, i]], default=0)  #SUM OF ALL 6 CRITERIA
    if t > 0:
        newcols_reformat4[i, :] = [max(p[s1[:, i]], default=0), max(p[s2[:, i]], default=0), max(p[s3[:, i]], default=0), max(p[s4[:, i]], default=0), max(p[s5[:, i]], default=0), max(p[s6[:, i]], default=0), t]

# SIRS - at each timepoint |  need: temp HR RR PaCO2 WBC 
s = reformat4t[['Temp_C', 'HR', 'RR', 'paCO2', 'WBC_count']].values

s1=np.array([(s[:, 0]>=38) | (s[:,0]<=36)])   # Count of points for all criteria of SIRS
s2=np.array([s[:, 1]>90])
s3=np.array([(s[:, 2]>=20) | (s[:, 3]<=32)])
s4=np.array([(s[:, 4]>=12) | (s[:, 4]<4)])
newcols_sirs = (1*s1) + (1*s2) + (1*s3) + (1*s4)

# Adds 2 cols for SOFA and SIRS
# Records values
reformat4t['SOFA'] = newcols_reformat4[:,-1]
reformat4t['SIRS'] = newcols_sirs[0]

FULL ICU -- COMPUTING SOME DERIVED VARIABLES: P/F, Shock Index, SOFA, SIRS...

In [44]:
# Check for patients with extreme UO = outliers = to be deleted (>40 litres of UO per 4h!!)
a = reformat4t['output_4hourly'] > 12000 
i = reformat4t[a]['icustayid'].unique() 
i = reformat4t['icustayid'].isin(i) 
reformat4t.drop(reformat4t.index[i], inplace=True) 

# Some have bili = 999999
a = reformat4t['Total_bili'] > 10000 
i = reformat4t[a]['icustayid'].unique()
i = reformat4t['icustayid'].isin(i) 
reformat4t.drop(reformat4t.index[i], inplace=True)

# Check for patients with extreme INTAKE = outliers = to be deleted (>10 litres of intake per 4h!!)
a = reformat4t['input_4hourly'] > 10000 
i = reformat4t[a]['icustayid'].unique()
i = reformat4t['icustayid'].isin(i) 
reformat4t.drop(reformat4t.index[i], inplace=True)
########################################################################

# Exclude early deaths from possible withdrawals 
print('Full ICU -- Excluding early deaths from possible withdrawals')
# Stats per patient
q = reformat4t['bloc']==1

num_of_trials = len(reformat4t['icustayid'].unique()) 
a = reformat4t[['icustayid', 'mortality_90d', 'max_dose_vaso', 'SOFA']].values
a = pd.DataFrame(a, columns = ['id', 'mortality_90d', 'vaso', 'sofa']) 
d = a.groupby(['id']).max() 
d_count = a.groupby(['id']).count()

# Find the patients who match the Sepsis 3 criteria
e = np.zeros(num_of_trials)
for i in range(num_of_trials):
    if d['mortality_90d'].iloc[i] == 1:
        ii = (reformat4t['icustayid'] == d.index[i]) & (reformat4t['bloc'] == d_count.iloc[i]['mortality_90d'])  #last row for this patient
        e[i] = np.sum((reformat4t['max_dose_vaso'][ii] == 0) & (d['vaso'].iloc[i] > 0.3) & (reformat4t['SOFA'][ii] >= d['sofa'].iloc[i]/2)) > 0
r = d.index[(e == 1) & (d_count['mortality_90d'] < 20)] # ids to be removed
ii = reformat4t['icustayid'].isin(r) 
reformat4t = reformat4t.loc[~ii] 

# Exclude patients who died in ICU during data collection period
print('Full ICU -- excluding patients who died in ICU during data collection period')
ii = (reformat4t['bloc'] == 1) & (reformat4t['died_within_48h_of_out_time'] == 1) & (reformat4t['delay_end_of_record_and_discharge_or_death'] < 24)
ii = reformat4t['icustayid'][ii][reformat4t['icustayid'][ii].isin(icustayidlist)]
ii = reformat4t['icustayid'].isin(ii)
reformat4t = reformat4t.loc[~ii]

Full ICU -- Excluding early deaths from possible withdrawals
Full ICU -- excluding patients who died in ICU during data collection period

In [48]:
print('Creating sepsis cohort')
# Create array with 1 row per icu admission
# Keep only patients with flagged sepsis (max sofa during time period of interest >= 2)
# Assumed baseline SOFA is zero
sepsis = np.zeros((30000,5)) #NOTE: For other cohorts, this size may have to be changed
irow = 0

bar_cohort = pyprind.ProgBar(len(icustayidlist))
for icustayid in icustayidlist:
    bar_cohort.update()
    ii = reformat4t['icustayid'] == icustayid 
    if sum(ii) > 0:
        sofa = reformat4t['SOFA'][ii]
        sirs = reformat4t['SIRS'][ii]
        sepsis[irow, 0] = icustayid
        sepsis[irow, 1] = reformat4t['mortality_90d'][ii].iloc[0] # 90-day mortality
        sepsis[irow, 2] = np.max(sofa)
        sepsis[irow, 3] = np.max(sirs)
        sepsis[irow, 4] = qstime[icustayid][0]   #time of onset of sepsis #icustayid-1 not done to keep it consistent with earlier verified use of qstime and 0 added as onset of sepsis index.
        irow += 1

sepsis = np.delete(sepsis, range(irow, len(sepsis)) ,axis=0) # Remove extra rows
sepsis = pd.DataFrame(sepsis, columns=['icustayid', 'morta_90d', 'max_sofa', 'max_sirs', 'sepsis_time'])

# Delete all non-septic patients
ii = sepsis['max_sofa'] < 2
sepsis = sepsis[~ii]
# Final count of patients included
print('Final patient count:', sepsis.shape[0])  

sepsis.to_csv('new_sepsis_mimiciii.csv', index=False)

Creating sepsis cohort
Warning: No valid output stream.
Final patient count: 18900

In [49]:
#gives an array with all unique charttime (1 per row) and all items in columns.
################## IMPORTANT !!!!!!!!!!!!!!!!!!
# Here we use -24 -> +48 to define the MDP
print('Sepsis Cohort -- Making an array with all unique charttime (1 per row) and all items in columns.')
reformat = np.nan*np.ones((2000000,69))  #final table 
qstime = dict()
winb4 = 25   #lower limit for inclusion of data (24h before time flag)
winaft = 49  # upper limit (48h after)
irow = 0  #recording row for summary table
bar = pyprind.ProgBar(sepsis.shape[0]+1)
for icustayidrow in range(1, sepsis.shape[0]+1):
    bar.update()
    qst = sepsis['sepsis_time'].iloc[icustayidrow-1] #;%,3); %flag for presumed infection
    icustayid = int(sepsis['icustayid'].iloc[icustayidrow-1])
    qstime[icustayid] = np.zeros(4)
    # CHARTEVENTS
    if (icustayid-200000) < 10000:
        temp=ce010
    elif (icustayid-200000) < 20000:
        temp=ce1020
    elif (icustayid-200000) < 30000:
        temp=ce2030
    elif (icustayid-200000) < 40000:
        temp=ce3040
    elif (icustayid-200000) < 50000:
        temp=ce4050
    elif (icustayid-200000) < 60000:
        temp=ce5060
    elif (icustayid-200000) < 70000:
        temp=ce6070
    elif (icustayid-200000) < 80000:
        temp=ce7080
    elif (icustayid-200000) < 90000:
        temp=ce8090
    else:
        temp=ce90100
    temp = temp[temp['icustay_id'] == icustayid]

    ii = (temp['charttime'] >= qst - (winb4+4)*3600) & (temp['charttime'] <= qst + (winaft+4)*3600) #time period of interest -4h and +4h
    temp = temp.loc[ii]   #only time period of interest

    # LAB EVENTS
    ii = labU['icustay_id'] == icustayid
    temp2 = labU.loc[ii]
    ii = (temp2['charttime'] >= qst - (winb4+4)*3600) & (temp2['charttime'] <= qst + (winaft+4)*3600) #time period of interest -4h and +4h
    temp2 = temp2.loc[ii]   #only time period of interest

    # Mech Vent + ?extubated
    ii = MV['icustay_id'] == icustayid
    temp3 = MV.loc[ii]
    ii = (temp3['charttime'] >= qst - (winb4+4)*3600) & (temp3['charttime'] <= qst + (winaft+4)*3600) # Time period of interest -4h and +4h
    temp3 = temp3.loc[ii]   #only time period of interest
    
    t = np.unique(pd.concat([temp['charttime'], temp2['charttime'], temp3['charttime']], ignore_index=True).values) # List of unique timestamps from all 3 sources / sorted in ascending order

    if len(t) > 0:
        for i in range(len(t)):
            # CHARTEVENTS
            ii = temp['charttime'] == t[i]
            col = temp.loc[ii, 'itemid']
            value = temp.loc[ii, 'valuenum']
            reformat[irow, 0] = i+1 # Timestep  
            reformat[irow, 1] = icustayid
            reformat[irow, 2] = t[i] # Charttime
            reformat[irow, 3] = qst  # Store the presumed onset time
            reformat[irow, 3+col.astype(int).values] = value.values # Store available values

            #LAB VALUES
            ii = temp2['charttime'] == t[i]
            col = temp2.loc[ii, 'itemid']
            value = temp2.loc[ii, 'valuenum']
            reformat[irow,31+col.astype(int).values] = value.values  #store available values
        
            #MV  
            ii = temp3['charttime'] == t[i]
            if np.nansum(ii) > 0:
                col = temp3.loc[ii, 'mechvent']
                value = temp3.loc[ii, 'extubated']
                reformat[irow, 67] = col.values[0] # Store available values
                reformat[irow, 68] = value.values[0] # Store available values
            else:
                reformat[irow, 67]= np.nan
                reformat[irow, 68]= np.nan
            irow += 1

        qstime[icustayid][0] = qst # Flag for presumed infection / this is time of sepsis if SOFA >=2 for this patient
        # WE SAVE FIRST and LAST TIMESTAMPS, in QSTIME, for each ICUSTAYID
        qstime[icustayid][1] = t[0]   # First timestamp
        qstime[icustayid][2] = t[-1]  # Last timestamp
        qstime[icustayid][3] = demog.loc[demog['icustay_id'] == icustayid, 'dischtime'].values[0] # Discharge time

reformat = np.delete(reformat, range(irow, len(reformat)) ,axis=0)  # Remove unused rows

Sepsis Cohort -- Making an array with all unique charttime (1 per row) and all items in columns.
Warning: No valid output stream.

In [50]:
print('Sepsis Cohort -- Handling outliers')

# Weight
reformat = deloutabove(reformat, 5, 300)

# Heart Rate
reformat = deloutabove(reformat, 8, 250)

# Blood Pressure
reformat = deloutabove(reformat, 9, 300)
reformat = deloutbelow(reformat, 10, 0)
reformat = deloutabove(reformat, 11, 200)
reformat = deloutbelow(reformat, 11, 0)
reformat = deloutabove(reformat, 11, 200)

# Respiratory Rate
reformat = deloutabove(reformat, 12, 80) 

# SpO2
reformat = deloutabove(reformat, 13, 150)
reformat[reformat[:, 13]>100, 13] = 100 
reformat = deloutbelow(reformat, 13, 50) 

# Temperature
reformat[(reformat[:, 14] > 90) & (np.isnan(reformat[:, 15])), 15] = reformat[(reformat[:, 14] > 90) & (np.isnan(reformat[:, 15])), 14]
reformat = deloutabove(reformat, 14, 90) 
reformat = deloutbelow(reformat, 14, 25) 

# interface / is in col 23
# FiO2
reformat = deloutabove(reformat, 23, 100)
reformat[reformat[:, 23] < 1 , 23] = reformat[reformat[:, 23] < 1 , 23]*100
reformat = deloutbelow(reformat, 23, 20) 
reformat = deloutabove(reformat, 24, 1.5)

# O2 FLOW
reformat = deloutabove(reformat, 25, 70)

# PEEP
reformat=deloutbelow(reformat, 26, 0)
reformat=deloutabove(reformat, 26, 40)

# Total Volume
reformat=deloutabove(reformat, 27, 1800)

# Mean Volume
reformat=deloutabove(reformat, 28, 50)

# Potassium
reformat=deloutbelow(reformat, 32, 1)
reformat=deloutabove(reformat, 32, 15)

# Sodium
reformat=deloutbelow(reformat, 33, 95)
reformat=deloutabove(reformat, 33, 178)

# Chloride
reformat=deloutbelow(reformat, 34, 70)
reformat=deloutabove(reformat, 34, 150)

# Glucose
reformat=deloutbelow(reformat, 35, 1)
reformat=deloutabove(reformat, 35, 1000) 

# Creatinine
reformat=deloutabove(reformat, 37, 150)

# Magnesium
reformat=deloutabove(reformat, 38, 10)

# Calcium
reformat=deloutabove(reformat, 39, 20)

# Ionized Calcium
reformat=deloutabove(reformat, 40, 5)

# CO2
reformat=deloutabove(reformat, 41, 120)

# SGPT/SGOT
reformat=deloutabove(reformat, 42, 10000)
reformat=deloutabove(reformat, 43, 10000)

# Hb/Ht
reformat=deloutabove(reformat, 50, 20)
reformat=deloutabove(reformat, 51, 65)

# White Blood Cells
reformat=deloutabove(reformat, 53, 500)

# Platelets
reformat=deloutabove(reformat, 54, 2000)

# INR
reformat=deloutabove(reformat, 58, 20)

# pH
reformat=deloutbelow(reformat, 59, 6.7)
reformat=deloutabove(reformat, 59, 8) 

# pO2
reformat=deloutabove(reformat, 60, 700)

# pCO2
reformat=deloutabove(reformat, 61, 200)

# Base Excess
reformat=deloutbelow(reformat, 62, -50)

# Lactate
reformat=deloutabove(reformat, 63, 30)

####################################################################
# More data manipulation / imputation from existing values
# Estimate GCS from RASS - data from Wesley JAMA 2003
reformat[(np.isnan(reformat[:, 6])) & (reformat[:, 7] >= 0), 6] = 15
reformat[(np.isnan(reformat[:, 6])) & (reformat[:, 7] == -1), 6] = 14
reformat[(np.isnan(reformat[:, 6])) & (reformat[:, 7] == -2), 6] = 12
reformat[(np.isnan(reformat[:, 6])) & (reformat[:, 7] == -3), 6] = 11
reformat[(np.isnan(reformat[:, 6])) & (reformat[:, 7] == -4), 6] = 6
reformat[(np.isnan(reformat[:, 6])) & (reformat[:, 7] == -5), 6] = 3

# FiO2
reformat[(~np.isnan(reformat[:, 23])) & (np.isnan(reformat[:, 24])), 24] = reformat[(~np.isnan(reformat[:, 23])) & (np.isnan(reformat[:, 24])), 23] / 100
reformat[(~np.isnan(reformat[:, 24])) & (np.isnan(reformat[:, 23])), 23] = reformat[(~np.isnan(reformat[:, 24])) & (np.isnan(reformat[:, 23])), 24] * 100

# ESTIMATE FiO2 /// with use of interface / device (cannula, mask, ventilator....)
print('Sepsis Cohort -- Doing sample and hold')
reformatsah = SAH(reformat, sample_and_hold, adjust=1) # do SAH first to handle this task, setting `adjust` to 1 since we added another column

# NO FiO2, YES O2 flow, no interface OR cannula
ii = np.where((np.isnan(reformatsah[:,23])) & (~np.isnan(reformatsah[:,25])) & ((reformatsah[:,22] == 0) | (reformatsah[:,22] == 2)))[0] #As np.where returns a tuple
reformat[ii[reformatsah[ii, 25] <= 15], 23] = 70
reformat[ii[reformatsah[ii, 25] <= 12], 23] = 62
reformat[ii[reformatsah[ii, 25] <= 10], 23] = 55
reformat[ii[reformatsah[ii, 25] <= 8], 23]  = 50
reformat[ii[reformatsah[ii, 25] <= 6], 23]  = 44
reformat[ii[reformatsah[ii, 25] <= 5], 23]  = 40
reformat[ii[reformatsah[ii, 25] <= 4], 23]  = 36
reformat[ii[reformatsah[ii, 25] <= 3], 23]  = 32
reformat[ii[reformatsah[ii, 25] <= 2], 23]  = 28
reformat[ii[reformatsah[ii, 25] <= 1], 23]  = 24

# NO FiO2, NO O2 flow, no interface OR cannula
ii = np.where((np.isnan(reformatsah[:, 23])) & np.isnan(reformatsah[:, 25]) & ((reformatsah[:, 22] == 0) | (reformatsah[:, 22] == 2)))[0]  #no fio2 given and o2flow given, no interface OR cannula
reformat[ii, 23] = 21

# NO FiO2, YES O2 flow, face mask OR.... OR ventilator (assume it's face mask)
ii = np.where((np.isnan(reformatsah[:,23])) & (~np.isnan(reformatsah[:,25])) & 
((reformatsah[:, 22]==1) | (reformatsah[:, 22]==3) | (reformatsah[:, 22]==4) | (reformatsah[:, 22]==5) | (reformatsah[:, 22]==6) | (reformatsah[:, 22]==9) | (reformatsah[:, 22]==10)))[0]
reformat[ii[reformatsah[ii, 25]<=15], 23] = 75
reformat[ii[reformatsah[ii, 25]<=12], 23] = 69
reformat[ii[reformatsah[ii, 25]<=10], 23] = 66
reformat[ii[reformatsah[ii, 25]<=8], 23]  = 58
reformat[ii[reformatsah[ii, 25]<=6], 23]  = 40
reformat[ii[reformatsah[ii, 25]<=4], 23]  = 36

# NO FiO2, NO O2 flow, face mask OR ....OR ventilator
ii = np.where(np.isnan(reformatsah[:, 23]) & np.isnan(reformatsah[:, 25]) & ((reformatsah[:, 22] == 1) | (reformatsah[:, 22] == 3) | 
(reformatsah[:, 22] == 4) | (reformatsah[:, 22] == 5) | (reformatsah[:, 22] == 6) | (reformatsah[:, 22] == 9) | (reformatsah[:, 22] == 10)))[0]  # No FiO2 given and O2 flow given, no interface OR cannula
reformat[ii, 23] = np.nan

# NO FiO2, YES O2 flow, Non rebreather mask
ii = np.where(np.isnan(reformatsah[:, 23]) & (~np.isnan(reformatsah[:, 25])) & (reformatsah[:, 22] == 7))[0]
reformat[ii[reformatsah[ii, 25] >= 10], 23] = 90
reformat[ii[reformatsah[ii, 25] >= 15], 23] = 100
reformat[ii[reformatsah[ii, 25] < 10], 23]  = 80
reformat[ii[reformatsah[ii, 25] <= 8], 23]  = 70
reformat[ii[reformatsah[ii, 25] <= 6], 23]  = 60

# NO FiO2, NO O2 flow, NRM
ii= np.where(np.isnan(reformatsah[:, 23]) & np.isnan(reformatsah[:, 25]) & (reformatsah[:, 22]==7))[0]  #no fio2 given and o2flow given, no interface OR cannula
reformat[ii, 23] = np.nan

# Update Fi02 columns again
ii = (~np.isnan(reformat[:, 23])) & (np.isnan(reformat[:, 24]))
reformat[ii, 24] = reformat[ii, 23]/100
ii = (~np.isnan(reformat[:, 24])) & (np.isnan(reformat[:, 24]))
reformat[ii, 23] = reformat[ii, 24]*100

# BLOOD PRESSURE
ii = (~np.isnan(reformat[:, 9])) & (~np.isnan(reformat[:, 10])) & np.isnan(reformat[:, 11])
reformat[ii, 11] = (3*reformat[ii, 10] - reformat[ii, 9])/2
ii = (~np.isnan(reformat[:, 9])) & (~np.isnan(reformat[:, 11])) & np.isnan(reformat[:, 10])
reformat[ii, 10] = (reformat[ii, 9] + 2*reformat[ii, 11])/3
ii = (~np.isnan(reformat[:, 10])) & (~np.isnan(reformat[:, 11])) & np.isnan(reformat[:, 9])
reformat[ii, 9] = 3*reformat[ii, 10] - 2*reformat[ii, 11]

# TEMPERATURE
# some values recorded in the wrong column
ii = (reformat[:, 15] > 25) & (reformat[:, 15] < 45) #tempF close to 37deg??!
reformat[ii, 14] = reformat[ii, 15]
reformat[ii, 15] = np.nan
ii = reformat[:, 14] >70  # TempC > 70, likely recorded in Farenheit
reformat[ii, 15] = reformat[ii, 14]
reformat[ii, 14] = np.nan
ii = (~np.isnan(reformat[:, 14])) & np.isnan(reformat[:, 15])
reformat[ii, 15] = reformat[ii, 14] * 1.8 + 32
ii = (~np.isnan(reformat[:, 14])) & np.isnan(reformat[:, 13])
reformat[ii, 14] = (reformat[ii, 15] - 32)/1.8

# Hb/Ht
ii = (~np.isnan(reformat[:, 50])) & np.isnan(reformat[:,51])
reformat[ii, 51] = (reformat[ii, 50] * 2.862) + 1.216
ii = (~np.isnan(reformat[:, 51])) & np.isnan(reformat[:,50])
reformat[ii, 50] = (reformat[ii, 51] - 1.216)/2.862

# BILIRUBIN
ii = (~np.isnan(reformat[:, 44])) & np.isnan(reformat[:,45])
reformat[ii, 45] = (reformat[ii, 44]*0.6934)-0.1752
ii = (~np.isnan(reformat[:, 45])) & np.isnan(reformat[:,44])
reformat[ii, 44] = (reformat[ii, 45] + 0.1752)/0.6934

Sepsis Cohort -- Handling outliers
Sepsis Cohort -- Doing sample and hold
Warning: No valid output stream.

In [51]:
print('SEPSIS COHORT -- SAMPLE AND HOLD on RAW DATA')
reformat = SAH(reformat[:, 0:69], sample_and_hold, adjust=1)  # Setting `adjust` to 1 to account for the added column for `presumed_onset`
#######################################################################
########################################################################
#                             DATA COMBINATION
########################################################################
print('Sepsis Cohort -- Data combination')
# WARNING: the time window of interest has been defined above (here -24 -> +48)! 
timestep = 4  # Resolution of timesteps, in hours
irow = 0   
icustayidlist = np.unique(reformat[:,1]).astype(np.int32)
reformat2 = np.nan*np.ones((reformat.shape[0], 86))  # Output array
num_patients = len(icustayidlist)  # Number of patients

# Adding 2 empty cols for future shock index=HR/SBP and P/F
reformat = np.hstack([reformat, np.nan*np.ones((reformat.shape[0], 2))])
bar = pyprind.ProgBar(num_patients)
for i in range(len(icustayidlist)):
    bar.update()
    icustayid = icustayidlist[i]  
    
    #CHARTEVENTS AND LAB VALUES
    temp = reformat[reformat[:,1] == icustayid,:]   # Subtable of interest
    beg = temp[0,2]   # Timestamp of first record
    
    #IV FLUID STUFF
    iv = inputMV['icustay_id'] == icustayid   # Rows of interest in inputMV
    input = inputMV[iv]    # Subset of interest
    iv = inputCV['icustay_id'] == icustayid   # Rows of interest in inputCV
    input2 = inputCV[iv]    # Subset of interest
    startt = input['starttime'] # Start of all infusions and boluses
    endt = input['endtime'] # End of all infusions and boluses
    rate = input['norm_rate_of_infusion']  # Rate of infusion (is NaN for boluses) || corrected for tonicity
    pread = inputpreadm[inputpreadm['icustay_id'] == icustayid]['inputpreadm'] # Preadmission volume

    input = input.values
    input2 = input2.values

    if len(pread) >0:             # Store the value, if available
        totvol = np.nansum(pread)
    else:
        totvol=0   # If not documented: it's zero

    # Compute volume of fluid given before start of record!!!
    t0 = 0
    t1 = beg
    # Input from MV (4 ways to compute)
    infu = np.nansum(rate*(endt-startt)*((endt<=t1) & (startt >= t0))/3600 + rate*(endt-t0)*((startt <= t0) & (endt <= t1) & (endt >= t0))/3600 +
                            rate*(t1-startt)*((startt >= t0) & (endt >=t1) & (startt <= t1))/3600 + rate*(t1-t0)*((endt >= t1) & (startt <= t0))/3600)
    # All boluses received during this timestep, from inputMV (need to check rate is NaN) and inputCV (simpler):
    bolus = np.nansum(input[np.isnan(input[:,5]) & (input[:,1] >= t0) & (input[:,1] <= t1),6]) + np.nansum(input2[(input2[:,1] >= t0) & (input2[:,1] <= t1),4])
    totvol = np.nansum([totvol,infu,bolus]) 
    
    #########################################################################################
    #VASOPRESSORS    
    iv = vasoMV['icustay_id'] == icustayid # rows of interest in vasoMV
    vaso1 = vasoMV[iv]    # subset of interest
    iv = vasoCV['icustay_id'] == icustayid   # rows of interest in vasoCV
    vaso2 = vasoCV[iv]    # subset of interest
    startv = vaso1['starttime'].values  # start of VP infusion
    endv = vaso1['endtime'].values      # end of VP infusions
    ratev = vaso1['rate_std'].values  # rate of VP infusion

    # DEMOGRAPHICS / gender, age, elixhauser, re-admit, onset time, died in hosp?, died within 48h of out_time (likely in ICU or soon after),
    # died within 90d after admission?, Length of stay after obs window     
    demogi = demog['icustay_id'] == icustayid
    dem = np.array(
            list(demog.gender[demogi].values) +
            list(demog.age[demogi].values) +
            list(demog.elixhauser[demogi].values) +
            list(demog.re_admission[demogi].values) + # Using corrected readmission (within 30 days of previous discharge)
            [temp[0,3]] +                    # Adding presumed sepsis onset
            list(demog.morta_hosp[demogi].values) + 
            list(abs(demog.dod[demogi].values - demog.outtime[demogi].values) < (24*3600*2)) +
            list(demog.morta_90[demogi].values) + 
            [(qstime[icustayid][3] - qstime[icustayid][2])/3600]      # Length of time after last observation and discharge?
            )
  
    # URINE OUTPUT
    iu = UO['icustay_id'] == icustayid   #rows of interest in inputMV
    output = UO[iu]    #subset of interest
    pread = UOpreadm[UOpreadm['icustay_id'] == icustayid-200000]['value'].values #preadmission UO ????????????????? Why no + 200000 for icustayid here?
    if len(pread) > 0:     #store the value, if available
        UOtot = np.nansum(pread)
    else:
        UOtot = 0
    # adding the volume of urine produced before start of recording!    
    UOnow = np.nansum(output[(output['charttime']>=t0) & (output['charttime'] <= t1)]['value'].values) #t0 and t1 defined above
    UOtot = np.nansum([UOtot, UOnow])
    
    # Loop over the relevant times for each patient where information is recorded
    for j in range(0, 79, timestep): # 0:timestep:79 % -28 until +52 = 80 hours in total (4 hours buffer on either side of our desired window)
        t0 = 3600*j + beg   # left limit of time window
        t1 = 3600*(j + timestep) + beg   # right limit of time window
        ii = (temp[:,2] >= t0) & (temp[:,2] <= t1)  # index of items in this time period
        if sum(ii)>0:
            # ICUSTAY_ID, OUTCOMES, DEMOGRAPHICS
            reformat2[irow,0] = (j/timestep)+1    # 'bloc' = timestep (1,2,3...)
            reformat2[irow,1] = icustayid         # icustay_ID
            reformat2[irow,2] = 3600*j+ beg       # t0 = lower limit of time window
            reformat2[irow,3:12] = dem            # demographics and outcomes
            
            # CHARTEVENTS and LAB VALUES (+ includes empty columns for shock index and P/F)
            value = temp[ii]  #records all values in this timestep
                
            if sum(ii) == 1:   # if only 1 row of values at this timestep
                reformat2[irow,12:79] = value[:,4:]
            else:
                reformat2[irow,12:79] = np.nanmean(value[:,4:], axis=0) # mean of all available values

            #VASOPRESSORS
            # for CV: dose at timestamps.
            # for MV: 4 possibles cases, each one needing a different way to compute the dose of VP actually administered:
            #----t0---start----end-----t1----
            #----start---t0----end----t1----
            #-----t0---start---t1---end
            #----start---t0----t1---end----
            #MV
            v = ((endv >= t0) & (endv <= t1)) | ((startv >= t0) & (endv<=t1)) | ((startv >= t0) & (startv <= t1))| ((startv <= t0) & (endv>=t1))
            #CV
            v2 = vaso2[(vaso2['charttime'] >= t0) & (vaso2['charttime'] <= t1)]['rate_std'].values
            if len(list(ratev[v]) +  list(v2)) > 0:
                v1 = np.nanmedian(list(ratev[v]) +  list(v2))
                v2 = np.nanmax(list(ratev[v]) + list(v2))
            else:
                v1 = np.nan
                v2 = np.nan
            if (~np.isnan(v1)) and (~np.isnan(v2)):
                reformat2[irow,79] = v1    #median of dose of VP
                reformat2[irow,80] = v2    #max dose of VP

            #INPUT FLUID
            #input from MV (4 ways to compute)
            infu = np.nansum(rate*(endt-startt)*((endt <= t1) & (startt >= t0))/3600 
                                          + rate*(endt-t0)*((startt <= t0) & (endt <= t1) & (endt >= t0))/3600 
                                          + rate*(t1-startt)*((startt >= t0) & (endt >= t1) & (startt <= t1))/3600 
                                          + rate*(t1-t0)*((endt >=t1) & (startt <= t0))/3600)
            #all boluses received during this timestep, from inputMV (need to check rate is NaN) and inputCV (simpler):
            bolus = np.nansum(input[(np.isnan(input[:,5])) & (input[:,1] >= t0) & (input[:,1] <= t1),6]) + np.nansum(input2[(input2[:,1] >= t0) & (input2[:,1] <= t1),4])
            #sum fluid given
            totvol = np.nansum([totvol, infu, bolus])
            reformat2[irow,81] = totvol    #total fluid given
            reformat2[irow,82] = np.nansum([infu, bolus])  #fluid given at this step
            
            #UO
            UOnow = np.nansum(output[(output['charttime'] >= t0) & (output['charttime'] <= t1)]['value'].values)
            UOtot = np.nansum([UOtot, UOnow])
            reformat2[irow,83] = UOtot    #total UO
            reformat2[irow,84] = np.nansum(UOnow)   #UO at this step

            #CUMULATED BALANCE
            reformat2[irow,85] = totvol - UOtot    #cumulated balance

            irow += 1

reformat2 = np.delete(reformat2, range(irow, len(reformat2)) ,axis=0)

SEPSIS COHORT -- SAMPLE AND HOLD on RAW DATA
Warning: No valid output stream.
Sepsis Cohort -- Data combination
Warning: No valid output stream.

/var/folders/c9/gz43vn156vs2b_jhrbcnkdnh0000gn/T/ipykernel_2532/4202867284.py:109: RuntimeWarning: Mean of empty slice
  reformat2[irow,12:79] = np.nanmean(value[:,4:], axis=0) # mean of all available values

In [52]:
dataheaders = [i[1:-1] for i in sample_and_hold.columns]
dataheaders.extend(['Shock_Index', 'PaO2_FiO2'])
dataheaders = ['bloc', 'icustayid', 'charttime', 'gender', 'age', 'elixhauser', 're_admission', 'presumed_onset', 'died_in_hosp', \
    'died_within_48h_of_out_time', 'mortality_90d', 'delay_end_of_record_and_discharge_or_death'] + \
    dataheaders + ['median_dose_vaso','max_dose_vaso','input_total','input_4hourly','output_total','output_4hourly','cumulated_balance']


reformat2t = pd.DataFrame(reformat2, columns=dataheaders)

# headers I want to keep
dataheaders5 = ['bloc', 'icustayid', 'charttime', 'gender', 'age', 'elixhauser', 're_admission', 'presumed_onset', 'died_in_hosp', 'died_within_48h_of_out_time', \
    'mortality_90d', 'delay_end_of_record_and_discharge_or_death', 'Weight_kg', 'GCS', 'HR', 'SysBP', 'MeanBP', 'DiaBP', 'RR', 'SpO2', 'Temp_C', 'FiO2_1', \
    'Potassium', 'Sodium', 'Chloride', 'Glucose', 'BUN', 'Creatinine', 'Magnesium', 'Calcium', 'Ionised_Ca', 'CO2_mEqL', 'SGOT', 'SGPT', 'Total_bili', 'Albumin', \
    'Hb', 'WBC_count', 'Platelets_count', 'PTT', 'PT', 'INR', 'Arterial_pH', 'paO2', 'paCO2', 'Arterial_BE', 'HCO3', 'Arterial_lactate', 'mechvent', 'Shock_Index', \
    'PaO2_FiO2', 'median_dose_vaso', 'max_dose_vaso', 'input_total', 'input_4hourly', 'output_total', 'output_4hourly', 'cumulated_balance']

reformat3t = reformat2t[dataheaders5].copy() 

## SOME DATA MANIPULATION BEFORE IMPUTATION
#CORRECT GENDER
reformat3t['gender'] = reformat3t['gender'] - 1

# CORRECT AGE > 200 yo
ii = reformat3t['age'] > 150*365.25
reformat3t.loc[ii,'age'] = 91.4*365.25

# FIX MECHVENT
reformat3t['mechvent'].fillna(0, inplace=True)
reformat3t.loc[reformat3t['mechvent'] > 0, 'mechvent'] = 1

# FIX Elixhauser missing values
reformat3t['elixhauser'].loc[np.isnan(reformat3t['elixhauser'])] = np.nanmedian(reformat3t['elixhauser'])   #use the median value / only a few missing data points 

# Vasopressors / no NAN
reformat3t['median_dose_vaso'].fillna(0, inplace=True)
reformat3t['max_dose_vaso'].fillna(0, inplace=True)

# Check missingness proportions here
miss = pd.DataFrame([np.sum(np.isnan(reformat3t.values), axis=0)/reformat3t.shape[0]], columns=reformat3t.columns)
# Fill the values temporarily with zeros, otherwise kNN imp doesnt work
reformat3t['Shock_Index'] = np.zeros(reformat3t.shape[0])
reformat3t['PaO2_FiO2'] = np.zeros(reformat3t.shape[0])

In [53]:
# Do linear interpolation where missingness is low (kNN imputation doesnt work if all rows have missing values)
reformat3 = reformat3t.values
miss = np.sum(np.isnan(reformat3), axis=0)/reformat3.shape[0]
ii = (miss>0) & (miss<0.05)  #less than 5% missingness
mechventcol = reformat3t.columns.tolist().index('mechvent')

for i in range(12, mechventcol): # correct col by col, otherwise it does it wrongly
    if ii[i]==1:
        reformat3[:, i] = fixgaps(reformat3[:, i])

reformat3t[reformat3t.columns[12:mechventcol]] = reformat3[:, 12:mechventcol]

# KNN IMPUTATION - Done on chunks of 10K records.
print('Sepsis Cohort -- KNN imputation with K = 1')

reformat3t_cols = reformat3t.columns.tolist()
mechventcol = reformat3t_cols.index('mechvent')
ref = np.copy(reformat3[:,12:mechventcol])  #columns of interest

bar_knn = pyprind.ProgBar(len(range(0,reformat3.shape[0],9999)))
for i in range(0,reformat3.shape[0],9999):   # Dataset divided in 10K rows chunks (otherwise too large)
    bar_knn.update()
    ref[i:i+9999,:] = KNN(k=1).fit_transform(ref[i:i+9999,:])

# Copy on the interpolated data
reformat3t[reformat3t_cols[12:mechventcol]] = ref 

reformat4t = reformat3t.copy()  # Make final table copy to compute derived features

Sepsis Cohort -- KNN imputation with K = 1
Warning: No valid output stream.
Imputing row 1/9999 with 20 missing, elapsed time: 15.943
Imputing row 101/9999 with 10 missing, elapsed time: 15.991
Imputing row 201/9999 with 17 missing, elapsed time: 16.028
Imputing row 301/9999 with 9 missing, elapsed time: 16.080
Imputing row 401/9999 with 12 missing, elapsed time: 16.137
Imputing row 501/9999 with 18 missing, elapsed time: 16.197
Imputing row 601/9999 with 23 missing, elapsed time: 16.254
Imputing row 701/9999 with 15 missing, elapsed time: 16.301
Imputing row 801/9999 with 8 missing, elapsed time: 16.349
Imputing row 901/9999 with 10 missing, elapsed time: 16.401
Imputing row 1001/9999 with 10 missing, elapsed time: 16.455
Imputing row 1101/9999 with 17 missing, elapsed time: 16.504
Imputing row 1201/9999 with 13 missing, elapsed time: 16.567
Imputing row 1301/9999 with 12 missing, elapsed time: 16.620
Imputing row 1401/9999 with 3 missing, elapsed time: 16.670
Imputing row 1501/9999 with 9 missing, elapsed time: 16.723
Imputing row 1601/9999 with 12 missing, elapsed time: 16.781
Imputing row 1701/9999 with 8 missing, elapsed time: 16.829
Imputing row 1801/9999 with 15 missing, elapsed time: 16.888
Imputing row 1901/9999 with 14 missing, elapsed time: 16.945
Imputing row 2001/9999 with 19 missing, elapsed time: 16.998
Imputing row 2101/9999 with 16 missing, elapsed time: 17.050
Imputing row 2201/9999 with 8 missing, elapsed time: 17.104
Imputing row 2301/9999 with 15 missing, elapsed time: 17.154
Imputing row 2401/9999 with 11 missing, elapsed time: 17.208
Imputing row 2501/9999 with 9 missing, elapsed time: 17.269
Imputing row 2601/9999 with 12 missing, elapsed time: 17.325
Imputing row 2701/9999 with 19 missing, elapsed time: 17.377
Imputing row 2801/9999 with 15 missing, elapsed time: 17.430
Imputing row 2901/9999 with 5 missing, elapsed time: 17.484
Imputing row 3001/9999 with 19 missing, elapsed time: 17.541
Imputing row 3101/9999 with 7 missing, elapsed time: 17.596
Imputing row 3201/9999 with 7 missing, elapsed time: 17.642
Imputing row 3301/9999 with 9 missing, elapsed time: 17.702
Imputing row 3401/9999 with 8 missing, elapsed time: 17.751
Imputing row 3501/9999 with 17 missing, elapsed time: 17.801
Imputing row 3601/9999 with 12 missing, elapsed time: 17.855
Imputing row 3701/9999 with 4 missing, elapsed time: 17.893
Imputing row 3801/9999 with 11 missing, elapsed time: 17.939
Imputing row 3901/9999 with 24 missing, elapsed time: 17.990
Imputing row 4001/9999 with 10 missing, elapsed time: 18.046
Imputing row 4101/9999 with 9 missing, elapsed time: 18.085
Imputing row 4201/9999 with 3 missing, elapsed time: 18.151
Imputing row 4301/9999 with 25 missing, elapsed time: 18.205
Imputing row 4401/9999 with 8 missing, elapsed time: 18.256
Imputing row 4501/9999 with 7 missing, elapsed time: 18.306
Imputing row 4601/9999 with 26 missing, elapsed time: 18.358
Imputing row 4701/9999 with 21 missing, elapsed time: 18.430
Imputing row 4801/9999 with 1 missing, elapsed time: 18.472
Imputing row 4901/9999 with 11 missing, elapsed time: 18.533
Imputing row 5001/9999 with 10 missing, elapsed time: 18.588
Imputing row 5101/9999 with 11 missing, elapsed time: 18.639
Imputing row 5201/9999 with 8 missing, elapsed time: 18.692
Imputing row 5301/9999 with 8 missing, elapsed time: 18.735
Imputing row 5401/9999 with 17 missing, elapsed time: 18.785
Imputing row 5501/9999 with 5 missing, elapsed time: 18.836
Imputing row 5601/9999 with 18 missing, elapsed time: 18.892
Imputing row 5701/9999 with 10 missing, elapsed time: 18.952
Imputing row 5801/9999 with 17 missing, elapsed time: 18.997
Imputing row 5901/9999 with 9 missing, elapsed time: 19.051
Imputing row 6001/9999 with 13 missing, elapsed time: 19.113
Imputing row 6101/9999 with 9 missing, elapsed time: 19.154
Imputing row 6201/9999 with 3 missing, elapsed time: 19.195
Imputing row 6301/9999 with 16 missing, elapsed time: 19.234
Imputing row 6401/9999 with 7 missing, elapsed time: 19.285
Imputing row 6501/9999 with 6 missing, elapsed time: 19.338
Imputing row 6601/9999 with 19 missing, elapsed time: 19.384
Imputing row 6701/9999 with 11 missing, elapsed time: 19.436
Imputing row 6801/9999 with 11 missing, elapsed time: 19.491
Imputing row 6901/9999 with 12 missing, elapsed time: 19.545
Imputing row 7001/9999 with 23 missing, elapsed time: 19.601
Imputing row 7101/9999 with 1 missing, elapsed time: 19.656
Imputing row 7201/9999 with 11 missing, elapsed time: 19.705
Imputing row 7301/9999 with 13 missing, elapsed time: 19.758
Imputing row 7401/9999 with 14 missing, elapsed time: 19.807
Imputing row 7501/9999 with 9 missing, elapsed time: 19.861
Imputing row 7601/9999 with 7 missing, elapsed time: 19.909
Imputing row 7701/9999 with 15 missing, elapsed time: 19.959
Imputing row 7801/9999 with 13 missing, elapsed time: 20.019
Imputing row 7901/9999 with 3 missing, elapsed time: 20.071
Imputing row 8001/9999 with 11 missing, elapsed time: 20.123
Imputing row 8101/9999 with 10 missing, elapsed time: 20.170
Imputing row 8201/9999 with 11 missing, elapsed time: 20.214
Imputing row 8301/9999 with 13 missing, elapsed time: 20.263
Imputing row 8401/9999 with 8 missing, elapsed time: 20.309
Imputing row 8501/9999 with 15 missing, elapsed time: 20.362
Imputing row 8601/9999 with 2 missing, elapsed time: 20.420
Imputing row 8701/9999 with 9 missing, elapsed time: 20.470
Imputing row 8801/9999 with 5 missing, elapsed time: 20.525
Imputing row 8901/9999 with 12 missing, elapsed time: 20.587
Imputing row 9001/9999 with 11 missing, elapsed time: 20.633
Imputing row 9101/9999 with 14 missing, elapsed time: 20.686
Imputing row 9201/9999 with 13 missing, elapsed time: 20.747
Imputing row 9301/9999 with 6 missing, elapsed time: 20.791
Imputing row 9401/9999 with 10 missing, elapsed time: 20.841
Imputing row 9501/9999 with 10 missing, elapsed time: 20.889
Imputing row 9601/9999 with 7 missing, elapsed time: 20.938
Imputing row 9701/9999 with 4 missing, elapsed time: 20.986
Imputing row 9801/9999 with 9 missing, elapsed time: 21.037
Imputing row 9901/9999 with 2 missing, elapsed time: 21.084
Imputing row 1/9999 with 13 missing, elapsed time: 15.039
Imputing row 101/9999 with 7 missing, elapsed time: 15.088
Imputing row 201/9999 with 8 missing, elapsed time: 15.127
Imputing row 301/9999 with 15 missing, elapsed time: 15.167
Imputing row 401/9999 with 18 missing, elapsed time: 15.208
Imputing row 501/9999 with 6 missing, elapsed time: 15.255
Imputing row 601/9999 with 8 missing, elapsed time: 15.308
Imputing row 701/9999 with 3 missing, elapsed time: 15.348
Imputing row 801/9999 with 19 missing, elapsed time: 15.400
Imputing row 901/9999 with 25 missing, elapsed time: 15.455
Imputing row 1001/9999 with 8 missing, elapsed time: 15.505
Imputing row 1101/9999 with 11 missing, elapsed time: 15.547
Imputing row 1201/9999 with 11 missing, elapsed time: 15.597
Imputing row 1301/9999 with 8 missing, elapsed time: 15.657
Imputing row 1401/9999 with 17 missing, elapsed time: 15.703
Imputing row 1501/9999 with 11 missing, elapsed time: 15.752
Imputing row 1601/9999 with 15 missing, elapsed time: 15.785
Imputing row 1701/9999 with 15 missing, elapsed time: 15.830
Imputing row 1801/9999 with 19 missing, elapsed time: 15.882
Imputing row 1901/9999 with 8 missing, elapsed time: 15.936
Imputing row 2001/9999 with 8 missing, elapsed time: 15.984
Imputing row 2101/9999 with 16 missing, elapsed time: 16.027
Imputing row 2201/9999 with 10 missing, elapsed time: 16.070
Imputing row 2301/9999 with 5 missing, elapsed time: 16.109
Imputing row 2401/9999 with 10 missing, elapsed time: 16.165
Imputing row 2501/9999 with 17 missing, elapsed time: 16.209
Imputing row 2601/9999 with 13 missing, elapsed time: 16.260
Imputing row 2701/9999 with 14 missing, elapsed time: 16.310
Imputing row 2801/9999 with 7 missing, elapsed time: 16.360
Imputing row 2901/9999 with 6 missing, elapsed time: 16.407
Imputing row 3001/9999 with 15 missing, elapsed time: 16.446
Imputing row 3101/9999 with 7 missing, elapsed time: 16.497
Imputing row 3201/9999 with 8 missing, elapsed time: 16.551
Imputing row 3301/9999 with 9 missing, elapsed time: 16.600
Imputing row 3401/9999 with 13 missing, elapsed time: 16.652
Imputing row 3501/9999 with 15 missing, elapsed time: 16.714
Imputing row 3601/9999 with 12 missing, elapsed time: 16.763
Imputing row 3701/9999 with 14 missing, elapsed time: 16.805
Imputing row 3801/9999 with 3 missing, elapsed time: 16.852
Imputing row 3901/9999 with 25 missing, elapsed time: 16.892
Imputing row 4001/9999 with 9 missing, elapsed time: 16.944
Imputing row 4101/9999 with 11 missing, elapsed time: 16.993
Imputing row 4201/9999 with 9 missing, elapsed time: 17.044
Imputing row 4301/9999 with 10 missing, elapsed time: 17.098
Imputing row 4401/9999 with 19 missing, elapsed time: 17.138
Imputing row 4501/9999 with 2 missing, elapsed time: 17.181
Imputing row 4601/9999 with 6 missing, elapsed time: 17.220
Imputing row 4701/9999 with 16 missing, elapsed time: 17.266
Imputing row 4801/9999 with 13 missing, elapsed time: 17.302
Imputing row 4901/9999 with 20 missing, elapsed time: 17.343
Imputing row 5001/9999 with 11 missing, elapsed time: 17.388
Imputing row 5101/9999 with 17 missing, elapsed time: 17.447
Imputing row 5201/9999 with 7 missing, elapsed time: 17.486
Imputing row 5301/9999 with 15 missing, elapsed time: 17.539
Imputing row 5401/9999 with 11 missing, elapsed time: 17.599
Imputing row 5501/9999 with 11 missing, elapsed time: 17.646
Imputing row 5601/9999 with 9 missing, elapsed time: 17.696
Imputing row 5701/9999 with 7 missing, elapsed time: 17.744
Imputing row 5801/9999 with 5 missing, elapsed time: 17.803
Imputing row 5901/9999 with 9 missing, elapsed time: 17.865
Imputing row 6001/9999 with 8 missing, elapsed time: 17.906
Imputing row 6101/9999 with 21 missing, elapsed time: 17.968
Imputing row 6201/9999 with 5 missing, elapsed time: 18.008
Imputing row 6301/9999 with 23 missing, elapsed time: 18.047
Imputing row 6401/9999 with 16 missing, elapsed time: 18.098
Imputing row 6501/9999 with 20 missing, elapsed time: 18.158
Imputing row 6601/9999 with 6 missing, elapsed time: 18.202
Imputing row 6701/9999 with 15 missing, elapsed time: 18.256
Imputing row 6801/9999 with 2 missing, elapsed time: 18.314
Imputing row 6901/9999 with 17 missing, elapsed time: 18.364
Imputing row 7001/9999 with 6 missing, elapsed time: 18.410
Imputing row 7101/9999 with 10 missing, elapsed time: 18.470
Imputing row 7201/9999 with 11 missing, elapsed time: 18.525
Imputing row 7301/9999 with 9 missing, elapsed time: 18.565
Imputing row 7401/9999 with 7 missing, elapsed time: 18.622
Imputing row 7501/9999 with 10 missing, elapsed time: 18.666
Imputing row 7601/9999 with 27 missing, elapsed time: 18.714
Imputing row 7701/9999 with 15 missing, elapsed time: 18.759
Imputing row 7801/9999 with 11 missing, elapsed time: 18.816
Imputing row 7901/9999 with 11 missing, elapsed time: 18.862
Imputing row 8001/9999 with 12 missing, elapsed time: 18.921
Imputing row 8101/9999 with 29 missing, elapsed time: 18.981
Imputing row 8201/9999 with 12 missing, elapsed time: 19.026
Imputing row 8301/9999 with 14 missing, elapsed time: 19.077
Imputing row 8401/9999 with 18 missing, elapsed time: 19.123
Imputing row 8501/9999 with 5 missing, elapsed time: 19.168
Imputing row 8601/9999 with 12 missing, elapsed time: 19.219
Imputing row 8701/9999 with 6 missing, elapsed time: 19.271
Imputing row 8801/9999 with 15 missing, elapsed time: 19.314
Imputing row 8901/9999 with 9 missing, elapsed time: 19.364
Imputing row 9001/9999 with 15 missing, elapsed time: 19.417
Imputing row 9101/9999 with 10 missing, elapsed time: 19.469
Imputing row 9201/9999 with 11 missing, elapsed time: 19.524
Imputing row 9301/9999 with 13 missing, elapsed time: 19.578
Imputing row 9401/9999 with 10 missing, elapsed time: 19.622
Imputing row 9501/9999 with 5 missing, elapsed time: 19.678
Imputing row 9601/9999 with 14 missing, elapsed time: 19.731
Imputing row 9701/9999 with 3 missing, elapsed time: 19.780
Imputing row 9801/9999 with 2 missing, elapsed time: 19.833
Imputing row 9901/9999 with 10 missing, elapsed time: 19.882
Imputing row 1/9999 with 15 missing, elapsed time: 15.061
Imputing row 101/9999 with 9 missing, elapsed time: 15.119
Imputing row 201/9999 with 25 missing, elapsed time: 15.176
Imputing row 301/9999 with 2 missing, elapsed time: 15.227
Imputing row 401/9999 with 19 missing, elapsed time: 15.272
Imputing row 501/9999 with 7 missing, elapsed time: 15.329
Imputing row 601/9999 with 10 missing, elapsed time: 15.383
Imputing row 701/9999 with 11 missing, elapsed time: 15.442
Imputing row 801/9999 with 9 missing, elapsed time: 15.490
Imputing row 901/9999 with 10 missing, elapsed time: 15.536
Imputing row 1001/9999 with 17 missing, elapsed time: 15.582
Imputing row 1101/9999 with 3 missing, elapsed time: 15.625
Imputing row 1201/9999 with 22 missing, elapsed time: 15.680
Imputing row 1301/9999 with 12 missing, elapsed time: 15.733
Imputing row 1401/9999 with 10 missing, elapsed time: 15.780
Imputing row 1501/9999 with 2 missing, elapsed time: 15.829
Imputing row 1601/9999 with 3 missing, elapsed time: 15.876
Imputing row 1701/9999 with 7 missing, elapsed time: 15.921
Imputing row 1801/9999 with 10 missing, elapsed time: 15.969
Imputing row 1901/9999 with 3 missing, elapsed time: 16.019
Imputing row 2001/9999 with 5 missing, elapsed time: 16.066
Imputing row 2101/9999 with 6 missing, elapsed time: 16.112
Imputing row 2201/9999 with 6 missing, elapsed time: 16.165
Imputing row 2301/9999 with 4 missing, elapsed time: 16.212
Imputing row 2401/9999 with 11 missing, elapsed time: 16.264
Imputing row 2501/9999 with 16 missing, elapsed time: 16.309
Imputing row 2601/9999 with 10 missing, elapsed time: 16.360
Imputing row 2701/9999 with 7 missing, elapsed time: 16.417
Imputing row 2801/9999 with 17 missing, elapsed time: 16.464
Imputing row 2901/9999 with 10 missing, elapsed time: 16.516
Imputing row 3001/9999 with 10 missing, elapsed time: 16.558
Imputing row 3101/9999 with 2 missing, elapsed time: 16.602
Imputing row 3201/9999 with 2 missing, elapsed time: 16.651
Imputing row 3301/9999 with 9 missing, elapsed time: 16.692
Imputing row 3401/9999 with 12 missing, elapsed time: 16.738
Imputing row 3501/9999 with 12 missing, elapsed time: 16.782
Imputing row 3601/9999 with 10 missing, elapsed time: 16.831
Imputing row 3701/9999 with 14 missing, elapsed time: 16.882
Imputing row 3801/9999 with 23 missing, elapsed time: 16.927
Imputing row 3901/9999 with 11 missing, elapsed time: 16.972
Imputing row 4001/9999 with 10 missing, elapsed time: 17.018
Imputing row 4101/9999 with 7 missing, elapsed time: 17.068
Imputing row 4201/9999 with 16 missing, elapsed time: 17.115
Imputing row 4301/9999 with 18 missing, elapsed time: 17.164
Imputing row 4401/9999 with 6 missing, elapsed time: 17.216
Imputing row 4501/9999 with 12 missing, elapsed time: 17.265
Imputing row 4601/9999 with 12 missing, elapsed time: 17.322
Imputing row 4701/9999 with 7 missing, elapsed time: 17.358
Imputing row 4801/9999 with 2 missing, elapsed time: 17.404
Imputing row 4901/9999 with 5 missing, elapsed time: 17.448
Imputing row 5001/9999 with 14 missing, elapsed time: 17.500
Imputing row 5101/9999 with 10 missing, elapsed time: 17.548
Imputing row 5201/9999 with 4 missing, elapsed time: 17.599
Imputing row 5301/9999 with 13 missing, elapsed time: 17.639
Imputing row 5401/9999 with 7 missing, elapsed time: 17.692
Imputing row 5501/9999 with 15 missing, elapsed time: 17.737
Imputing row 5601/9999 with 15 missing, elapsed time: 17.784
Imputing row 5701/9999 with 2 missing, elapsed time: 17.838
Imputing row 5801/9999 with 13 missing, elapsed time: 17.885
Imputing row 5901/9999 with 5 missing, elapsed time: 17.933
Imputing row 6001/9999 with 11 missing, elapsed time: 17.993
Imputing row 6101/9999 with 25 missing, elapsed time: 18.048
Imputing row 6201/9999 with 8 missing, elapsed time: 18.101
Imputing row 6301/9999 with 9 missing, elapsed time: 18.143
Imputing row 6401/9999 with 6 missing, elapsed time: 18.192
Imputing row 6501/9999 with 6 missing, elapsed time: 18.229
Imputing row 6601/9999 with 12 missing, elapsed time: 18.269
Imputing row 6701/9999 with 10 missing, elapsed time: 18.314
Imputing row 6801/9999 with 6 missing, elapsed time: 18.360
Imputing row 6901/9999 with 1 missing, elapsed time: 18.405
Imputing row 7001/9999 with 5 missing, elapsed time: 18.461
Imputing row 7101/9999 with 9 missing, elapsed time: 18.510
Imputing row 7201/9999 with 18 missing, elapsed time: 18.551
Imputing row 7301/9999 with 23 missing, elapsed time: 18.604
Imputing row 7401/9999 with 6 missing, elapsed time: 18.659
Imputing row 7501/9999 with 11 missing, elapsed time: 18.715
Imputing row 7601/9999 with 5 missing, elapsed time: 18.761
Imputing row 7701/9999 with 11 missing, elapsed time: 18.804
Imputing row 7801/9999 with 10 missing, elapsed time: 18.848
Imputing row 7901/9999 with 19 missing, elapsed time: 18.933
Imputing row 8001/9999 with 11 missing, elapsed time: 18.992
Imputing row 8101/9999 with 12 missing, elapsed time: 19.047
Imputing row 8201/9999 with 11 missing, elapsed time: 19.088
Imputing row 8301/9999 with 7 missing, elapsed time: 19.132
Imputing row 8401/9999 with 8 missing, elapsed time: 19.192
Imputing row 8501/9999 with 12 missing, elapsed time: 19.227
Imputing row 8601/9999 with 17 missing, elapsed time: 19.276
Imputing row 8701/9999 with 4 missing, elapsed time: 19.326
Imputing row 8801/9999 with 12 missing, elapsed time: 19.377
Imputing row 8901/9999 with 7 missing, elapsed time: 19.435
Imputing row 9001/9999 with 12 missing, elapsed time: 19.474
Imputing row 9101/9999 with 16 missing, elapsed time: 19.522
Imputing row 9201/9999 with 16 missing, elapsed time: 19.581
Imputing row 9301/9999 with 8 missing, elapsed time: 19.630
Imputing row 9401/9999 with 10 missing, elapsed time: 19.668
Imputing row 9501/9999 with 7 missing, elapsed time: 19.713
Imputing row 9601/9999 with 1 missing, elapsed time: 19.771
Imputing row 9701/9999 with 10 missing, elapsed time: 19.817
Imputing row 9801/9999 with 24 missing, elapsed time: 19.866
Imputing row 9901/9999 with 18 missing, elapsed time: 19.917
Imputing row 1/9999 with 24 missing, elapsed time: 15.134
Imputing row 101/9999 with 2 missing, elapsed time: 15.187
Imputing row 201/9999 with 10 missing, elapsed time: 15.237
Imputing row 301/9999 with 10 missing, elapsed time: 15.295
Imputing row 401/9999 with 20 missing, elapsed time: 15.354
Imputing row 501/9999 with 10 missing, elapsed time: 15.410
Imputing row 601/9999 with 11 missing, elapsed time: 15.461
Imputing row 701/9999 with 15 missing, elapsed time: 15.513
Imputing row 801/9999 with 12 missing, elapsed time: 15.559
Imputing row 901/9999 with 14 missing, elapsed time: 15.607
Imputing row 1001/9999 with 6 missing, elapsed time: 15.652
Imputing row 1101/9999 with 6 missing, elapsed time: 15.694
Imputing row 1201/9999 with 12 missing, elapsed time: 15.746
Imputing row 1301/9999 with 17 missing, elapsed time: 15.798
Imputing row 1401/9999 with 33 missing, elapsed time: 15.844
Imputing row 1501/9999 with 25 missing, elapsed time: 15.896
Imputing row 1601/9999 with 21 missing, elapsed time: 15.942
Imputing row 1701/9999 with 2 missing, elapsed time: 15.993
Imputing row 1801/9999 with 12 missing, elapsed time: 16.035
Imputing row 1901/9999 with 4 missing, elapsed time: 16.083
Imputing row 2001/9999 with 16 missing, elapsed time: 16.130
Imputing row 2101/9999 with 10 missing, elapsed time: 16.178
Imputing row 2201/9999 with 6 missing, elapsed time: 16.224
Imputing row 2301/9999 with 8 missing, elapsed time: 16.271
Imputing row 2401/9999 with 9 missing, elapsed time: 16.314
Imputing row 2501/9999 with 29 missing, elapsed time: 16.373
Imputing row 2601/9999 with 4 missing, elapsed time: 16.417
Imputing row 2701/9999 with 6 missing, elapsed time: 16.465
Imputing row 2801/9999 with 2 missing, elapsed time: 16.513

In [56]:
# Recompute P/F with no missing values...
reformat4t['PaO2_FiO2'] = reformat4t['paO2'] / reformat4t['FiO2_1']

# Recompute SHOCK INDEX without NAN and INF
reformat4t['Shock_Index'] = reformat4t['HR'] / reformat4t['SysBP']
reformat4t.loc[np.isinf(reformat4t['Shock_Index']), 'Shock_Index'] = np.NaN
d = np.nanmean(reformat4t['Shock_Index'])
reformat4t['Shock_Index'].fillna(d, inplace=True)
shock_idx = reformat4t['Shock_Index'] >= np.quantile(reformat4t['Shock_Index'], 0.999)
reformat4t.loc[shock_idx, 'Shock_Index'] = np.quantile(reformat4t['Shock_Index'], 0.999)

# SOFA - at each timepoint we need (in this order):  
# P/F,  MV,  PLT,  TOT_BILI,  MAP,  NORAD(max),  GCS, CR,  UO
s = reformat4t[['PaO2_FiO2', 'Platelets_count', 'Total_bili', 'MeanBP', 'max_dose_vaso', 'GCS', 'Creatinine', 'output_4hourly']].values
p = np.arange(5)
s1 = np.array([s[:, 0] > 400, (s[:, 0] >= 300) & (s[:, 0] < 400), (s[:, 0] >= 200) & (s[:, 0] < 300), (s[:, 0] >= 100) & (s[:, 0] < 200), s[:, 0] < 100])  # Count of points for all 6 criteria of SOFA
s2 = np.array([s[:, 1] > 150, (s[:, 1] >= 100) & (s[:, 1] < 150), (s[:, 1] >= 50) & (s[:, 1] < 100), (s[:, 1] >= 20) & (s[:, 1] < 50), s[:, 1] < 20])
s3 = np.array([s[:, 2] < 1.2, (s[:, 2] >= 1.2) & (s[:, 2] < 2), (s[:, 2] >= 2) & (s[:, 2] < 6), (s[:, 2] >= 6) & (s[:, 2] < 12), s[:, 2] > 12])
s4 = np.array([s[:, 3] >= 70, (s[:, 3] < 70) & (s[:, 3] >= 65), (s[:, 3] < 65), (s[:, 4] > 0) & (s[:, 4] <= 0.1), s[:, 4] > 0.1])
s5 = np.array([s[:, 5] > 14, (s[:, 5] > 12) & (s[:, 5] <= 14), (s[:, 5] > 9) & (s[:, 5] <= 12), (s[:, 5] > 5) & (s[:, 5] <= 9), s[:, 5] <= 5])
s6 = np.array([s[:, 6] < 1.2, (s[:, 6] >= 1.2) & (s[:, 6] < 2), (s[:, 6] >= 2) & (s[:, 6] < 3.5), ((s[:, 6] >= 3.5) & (s[:, 6] < 5)) | (s[:, 7] < 84), (s[:, 6] > 5) | (s[:, 7] < 34)])

num_columns = reformat4t.shape[1]  # Number of variables in data
newcols_reformat4 = np.zeros((reformat4t.shape[0], 7))
for i in range(reformat4t.shape[0]):
    t = max(p[s1[:, i]], default=0) + max(p[s2[:, i]], default=0) + max(p[s3[:, i]], default=0) + max(p[s4[:, i]], default=0) + max(p[s5[:, i]], default=0) + max(p[s6[:, i]], default=0)  # SUM OF ALL 6 CRITERIA
    if t > 0:
        newcols_reformat4[i, :] = [max(p[s1[:, i]], default=0), max(p[s2[:, i]], default=0), max(p[s3[:, i]], default=0), max(p[s4[:, i]], default=0), max(p[s5[:, i]], default=0), max(p[s6[:, i]], default=0), t]

# SIRS - at each timepoint |  need: temp HR RR PaCO2 WBC 
s = reformat4t[['Temp_C', 'HR', 'RR', 'paCO2', 'WBC_count']].values
s1 = np.array([(s[:, 0] >= 38) | (s[:, 0] <= 36)])  # Count of points for all criteria of SIRS
s2 = np.array([s[:, 1] > 90])
s3 = np.array([(s[:, 2] >= 20) | (s[:, 3] <= 32)])
s4 = np.array([(s[:, 4] >= 12) | (s[:, 4] < 4)])
newcols_sirs = (1 * s1) + (1 * s2) + (1 * s3) + (1 * s4)

# More IO corrections
reformat4t.loc[reformat4t['input_total'] < 0, 'input_total'] = 0
reformat4t.loc[reformat4t['input_4hourly'] < 0, 'input_4hourly'] = 0

# Records values
reformat4t['SOFA'] = newcols_reformat4[:, -1]
reformat4t['SIRS'] = newcols_sirs[0]

In [58]:
MIMICtable = reformat4t.copy()
MIMICtable.to_csv('MIMICtable.csv', index=False)

#################   Convert training data and compute conversion factors    ######################

# all 47 columns of interest + additional meta columns to easier associate trajectories with other patient auxiliary info (eg. notes)
colmeta = ['presumed_onset', 'charttime', 'icustayid']  # Meta-data around patient stay
colbin = ['gender', 'mechvent', 'max_dose_vaso', 're_admission']  # Binary features
# Patient features that will be z-normalize
colnorm = ['age', 'Weight_kg', 'GCS', 'HR', 'SysBP', 'MeanBP', 'DiaBP', 'RR', 'Temp_C', 'FiO2_1',
        'Potassium', 'Sodium', 'Chloride', 'Glucose', 'Magnesium', 'Calcium', 'Hb', \
        'WBC_count', 'Platelets_count', 'PTT', 'PT', 'Arterial_pH', 'paO2', 'paCO2',\
        'Arterial_BE', 'HCO3', 'Arterial_lactate', 'SOFA', 'SIRS', 'Shock_Index',\
        'PaO2_FiO2', 'cumulated_balance']
# Patient features that will be log-normalized
collog=['SpO2', 'BUN', 'Creatinine', 'SGOT', 'SGPT', 'Total_bili', 'INR',
        'input_total', 'input_4hourly', 'output_total', 'output_4hourly']

# find patients who died in ICU during data collection period
icustayidlist = MIMICtable['icustayid']
icuuniqueids = icustayidlist.unique() #list of unique icustayids from MIMIC

MIMICraw = MIMICtable[colmeta + colbin + colnorm + collog]
MIMICraw = MIMICraw.values  # RAW values
MIMICzs = np.hstack([MIMICtable[colmeta].values, MIMICtable[colbin].values - 0.5, stats.zscore(MIMICtable[colnorm].values), 
    stats.zscore(np.log(0.1 + MIMICtable[collog].values))])

MIMICzs[:,5] = np.log(MIMICzs[:, 5] + 0.6)  # MAX DOSE NORAD 
MIMICzs[:,46] = 2 * MIMICzs[:,46]  # Increase weight of this variable

# compute conversion factors using MIMIC data
a = MIMICtable['input_4hourly'].values  # IV fluid
a = stats.rankdata(a[a > 0]) / len(a[a > 0]) # excludes zero fluid (will be action 1)
iof = np.floor((a + 0.2499999999) * 4).astype(int) #converts iv volume in 4 actions
a = MIMICtable['input_4hourly'] > 0 # location of non-zero fluid in big matrix
io = np.ones(MIMICtable.shape[0]) # array of ones, by default     
io[a] = iof + 1 # where more than zero fluid given: save actual action

vc = MIMICtable['max_dose_vaso'].values
vcr = stats.rankdata(vc[vc != 0]) / len(vc[vc != 0])
vcr = np.floor((vcr + 0.249999999999) * 4)
vcr[vcr == 0] = 1
vc[vc != 0] = vcr + 1
vc[vc == 0] = 1

actions = (io - 1) * 5 + (vc - 1)

# Process MIMICzs into trajectory data for later use
MIMICzs = pd.DataFrame(MIMICzs, columns=colmeta + colbin + colnorm + collog)
meta_df = pd.DataFrame(MIMICzs[colmeta].values, columns = colmeta)
ob_df = pd.DataFrame(MIMICzs[colbin + colnorm + collog].values, columns=colbin + colnorm + collog)
ac_df = pd.DataFrame(actions, columns=['action'])
raw_data_df = MIMICtable.copy()
num_actions = 25
outcome_key = 'died_within_48h_of_out_time' # Should be either 'died_within_48h_of_out_time' or 'mortality_90d'
meta_cols = meta_df.columns.tolist()
ob_cols = ob_df.columns.tolist()
raw_data_df['traj'] = (raw_data_df['bloc'] == 1).cumsum().values
meta_df['traj'] = (raw_data_df['bloc'] == 1).cumsum().values
ob_df['traj'] = (raw_data_df['bloc'] == 1).cumsum().values
ac_df['traj'] = (raw_data_df['bloc'] == 1).cumsum().values
trajectories = raw_data_df['traj'].unique()
data = {}
data['meta_cols'] = meta_cols
data['obs_cols'] = ob_cols
data['traj'] = {}

print('Sepsis Cohort -- Making trajectory data')
bar = pyprind.ProgBar(len(trajectories))
for i in trajectories:
    bar.update()
    data['traj'][i] = {}
    data['traj'][i]['meta'] = meta_df[meta_df['traj'] == i][meta_cols].values.T
    data['traj'][i]['obs'] = ob_df[ob_df['traj'] == i][ob_cols].values.T
    data['traj'][i]['actions'] = ac_df[ac_df['traj'] == i]['action'].values.astype(np.int32)
    data['traj'][i]['outcome'] = raw_data_df[raw_data_df['traj'] == i][outcome_key].values[0]
    data['traj'][i]['rewards'] = np.zeros(len(data['traj'][i]['actions']))
    data['traj'][i]['rewards'][-1] = (1 - 2 * data['traj'][i]['outcome'])

print('Sepsis Cohort -- Making final output file')
col_names = ['traj', 'step']
col_names.extend(['m:' + i for i in data['meta_cols']])
col_names.extend(['o:' + i for i in data['obs_cols']])
col_names.append('a:action')
col_names.append('r:reward')
all_data = []
bar = pyprind.ProgBar(len(data['traj'].keys()))
for i in data['traj'].keys():
    bar.update()
    for ctr in range(data['traj'][i]['actions'].shape[0]):
        all_data.append([])
        all_data[-1].append(i)
        all_data[-1].append(ctr)
        for m_index in range(data['traj'][i]['meta'].shape[0]):
            all_data[-1].append(data['traj'][i]['meta'][m_index, ctr])
        for o_index in range(data['traj'][i]['obs'].shape[0]):
            all_data[-1].append(data['traj'][i]['obs'][o_index, ctr])
        all_data[-1].append(data['traj'][i]['actions'][ctr])
        all_data[-1].append(data['traj'][i]['rewards'][ctr])
df = pd.DataFrame(all_data, columns=col_names)
df.to_csv('sepsis_final_data_withTimes.csv', index=False)

raw_df = pd.DataFrame(MIMICraw, columns=colmeta + colbin + colnorm + collog)
meta_df = raw_df[colmeta]
meta_df = pd.DataFrame(meta_df.values, columns=colmeta)
ob_df = raw_df[colbin + colnorm + collog]
ob_df = pd.DataFrame(ob_df.values, columns=colbin + colnorm + collog)
ac_df = pd.DataFrame(actions, columns=['action'])
raw_data_df = MIMICtable.copy()
num_actions = 25
outcome_key = 'died_within_48h_of_out_time' # Should be either 'died_within_48h_of_out_time' or 'mortality_90d'
meta_cols = meta_df.columns.tolist()
ob_cols = ob_df.columns.tolist()
raw_data_df['traj'] = (raw_data_df['bloc'] == 1).cumsum().values
meta_df['traj'] = (raw_data_df['bloc'] == 1).cumsum().values
ob_df['traj'] = (raw_data_df['bloc'] == 1).cumsum().values
ac_df['traj'] = (raw_data_df['bloc'] == 1).cumsum().values
trajectories = raw_data_df['traj'].unique()
data = {}
data['meta_cols'] = meta_cols
data['obs_cols'] = ob_cols
data['traj'] = {}

print('Sepsis Cohort -- Making RAW trajectory data')
bar = pyprind.ProgBar(len(trajectories))
for i in trajectories:
    bar.update()
    data['traj'][i] = {}
    data['traj'][i]['meta'] = meta_df[meta_df['traj'] == i][meta_cols].values.T
    data['traj'][i]['obs'] = ob_df[ob_df['traj'] == i][ob_cols].values.T
    data['traj'][i]['actions'] = ac_df[ac_df['traj'] == i]['action'].values.astype(np.int32)
    data['traj'][i]['outcome'] = raw_data_df[raw_data_df['traj'] == i][outcome_key].values[0]
    data['traj'][i]['rewards'] = np.zeros(len(data['traj'][i]['actions']))
    data['traj'][i]['rewards'][-1] = (1 - 2 * data['traj'][i]['outcome'])

print('Sepsis Cohort -- Making final RAW output file')
col_names = ['traj', 'step']
col_names.extend(['m:' + i for i in data['meta_cols']])
col_names.extend(['o:' + i for i in data['obs_cols']])
col_names.append('a:action')
col_names.append('r:reward')
all_data = []
bar = pyprind.ProgBar(len(data['traj'].keys()))
for i in data['traj'].keys():
    bar.update()
    for ctr in range(data['traj'][i]['actions'].shape[0]):
        all_data.append([])
        all_data[-1].append(i)
        all_data[-1].append(ctr)
        for m_index in range(data['traj'][i]['meta'].shape[0]):
            all_data[-1].append(data['traj'][i]['meta'][m_index, ctr])
        for o_index in range(data['traj'][i]['obs'].shape[0]):
            all_data[-1].append(data['traj'][i]['obs'][o_index, ctr])
        all_data[-1].append(data['traj'][i]['actions'][ctr])
        all_data[-1].append(data['traj'][i]['rewards'][ctr])
df = pd.DataFrame(all_data, columns=col_names)
df.to_csv('sepsis_final_data_RAW_withTimes.csv', index=False)

Sepsis Cohort -- Making trajectory data
Warning: No valid output stream.
Sepsis Cohort -- Making final output file
Warning: No valid output stream.
Sepsis Cohort -- Making RAW trajectory data
Warning: No valid output stream.
Sepsis Cohort -- Making final RAW output file
Warning: No valid output stream.